### ISSUE TITLE
rename 'proxy'

### ISSUE THREAD

**Issue by rade** [weaveworks/weave#1019]
'proxy' is both too generic and too specific (for some users it means 'http proxy'). 'relay' has been suggested as an alternative name.

**Comment by squaremo** [comment]
"Relay" is not bad, assuming it isn't also a commonly-understood shorthand like "proxy". On the other hand, it doesn't give the reader much to go on, and it sounds like a bit of networking kit rather than a bit of Docker integration kit.

At risk of making things harder,

 * "Docker [[remote] API] proxy" (probably too cumbersome, though specific)
 * "Weave remote" (it's not really a remote for _weeeave_; weaveexec is, though ...)
 * "[API] interceptor" hmmmmm
 * possibly overthinking this

**Comment by squaremo** [comment]
Some other suggestions that came up:

 * "weave hook"
 * "Weave Docker workaround"
 * "weave all your containers"

I am starting to like just calling it the "API proxy", which is accurate and not too long.

**Comment by rade** [comment]
If "API proxy" is the best we can come up with then I'd rather leave it as is.

**Comment by rade** [comment]
Also, `weave launch-api-proxy` and `eval $(weave api-proxy-env)` are just needlessly verbose.

**Comment by awh** [comment]
* "weave injector"
* "weave link"
* "weave mod"
* "weave augment"/"weave aug"
* "weave extender"/"weavex"

**Comment by rade** [comment]
all inferior to proxy, IMO.

I'm tempted to close this as wontfix.

**Comment by squaremo** [comment]
Perhaps we could introduce it in documentation entry points as the "Docker API proxy", and thereafter (and in code) just use "proxy".

**Comment by paulbellamy** [comment]
"Docker Adapter"

**Comment by rade** [comment]
> Perhaps we could introduce it in documentation entry points as the "Docker API proxy"

That seems like a worthwhile compromise.

**Comment by 2opremio** [comment]
wrapper, facade, bridge (probably not, since it can be confused with a network interface), envelope (probably, not since it can be confused with some payload)?
