### ISSUE TITLE
Support alternative shells for `weave env`

### ISSUE THREAD

**Issue by paulbellamy** [weaveworks/weave#1269]
Certain shells (e.g. fish) don't support "export". For what to do, see `boot2docker shellinit`.

**Comment by peterbourgon** [comment]
It seems that only fish is a unique snowflake.

```go
func printExportUnix(values map[string]string) {
	for name, value := range values {
		switch filepath.Base(os.Getenv("SHELL")) {
		case "fish":
			if value == "" {
				fmt.Printf("    set -e %s\n", name)
			} else {
				fmt.Printf("    set -x %s %s\n", name, value)
			}
		default: // default command to export variables POSIX shells, like bash, zsh, etc.
			if value == "" {
				fmt.Printf("    unset %s\n", name)
			} else {
				fmt.Printf("    export %s=%s\n", name, value)
			}
		}
	}
}
```

https://github.com/boot2docker/boot2docker-cli/blob/master/cmds.go#L218-L233

**Comment by dpw** [comment]
There are lots of weird and wonderful shells out there.  If boot2docker supports fish, I'd guess that means that someone cared enough to contribute fish support, rather than that fish is the only shell that needs special handing.

So I'm sceptical that trying to support non-POSIX shells is worthwhile.  People can always do `sh -c 'eval $(weave env); exec my_favorite_sh'` if they want.

**Comment by peterbourgon** [comment]
@dpw :+1:

**Comment by paulbellamy** [comment]
or use `docker $(weave config) ...`

**Comment by rade** [comment]
> or use `docker $(weave config)` ...

You are assuming here that the shell hasn't invented a different way of passing command line args. ;)
