### ISSUE TITLE
`weave reset` fails with "Cannot find device" on kernel 4.2+

### ISSUE THREAD

**Issue by rade** [weaveworks/weave#1364]
Extracted from #1356...

@MaximeHeckel has seen `weave --local reset` fail with `Cannot find device "vethwepl14191@if322"`. This can happen when a container dies during reset, which is what #1356 is about, but it could also happen if somehow our interface name extraction is broken - that `@if322` in the interface name looks weird.

@MaximeHeckel as @bboreham said, please get us the output of `ip link show` from the host. Also what OS and kernel is that host running? And what version of iptables (`ip -V`)?

**Comment by MaximeHeckel** [comment]
@rade The user might have reset his host, so not sure I can provide that to you. I'm going to check with him.

**Comment by rade** [comment]
@MaximeHeckel I am going to close this; if you ever encounter such strange interface names in the wild again, please re-open with some extra info.

**Comment by dpw** [comment]
It looks to me that an interface name like that will occur in the `ip link` output for anyone using kernel 4.1 or later:

https://github.com/torvalds/linux/commit/a45253b

See also:

https://github.com/shemminger/iproute2/commit/ccdcbf35

(That iproute2 change appeared in v4.0.0, or a snapshot after 20150217)

**Comment by rade** [comment]
> https://github.com/shemminger/iproute2/commit/ccdcbf35

Hmm. According to that, it was outputing `@` before too. What am I missing?

In the weave script we extract the name and then call `ip link del` on it. Will s.t. like `ip link del vethwepl14191@if322` break?

**Comment by dpw** [comment]
> Hmm. According to that, it was outputing @ before too. What am I missing?

The kernel change is the crucial one, because it causes the IFLA_LINK attribute to be reported for veth netdevs.  `ip link` *could* output '@' before, going back to when it migrated to git, but until that kernel change it wouldn't do so for veths.

That iproute2 commit is interesting because it introduces `@ifNNN` (to denote a unique name for a netdev in a different namespace).  So it ties down the relevant version of iproute2 a bit.

(It also shows that there are moves to make network namespaces and associated plumbing a bit more transparent.  Which is nice - it might have made debugging the dangling netns problems a bit easier.  It's just  a shame the improvements are not yet widely deployed..)

> In the weave script we extract the name and then call ip link del on it. Will s.t. like ip link del vethwepl14191@if322 break?

Yes, it will break.  The part after '@' is informational.  It's not part of the netdev name in any sense, and no `ip` subcommands accept it.  We'll need to strip it off.

**Comment by rade** [comment]
@dpw thanks for tracking down the cause.
