### ISSUE TITLE
Determine bridge and container network interface requirements

### ISSUE THREAD

**Issue by awh** [weaveworks/weave#1421]
In certain types of deployment (e.g. CNI) weave will not be in charge of creating bridge devices and container network interfaces. An analysis of weave must be performed to identify specific problems and document them as issues for resolution.
- [ ] #1255 - Don't rely on disabling TSO

**Comment by bboreham** [comment]
I think when this was filed the thinking was that we could piggy-back on the CNI 'bridge' plugin.  Since then we have implemented our own Weave Net CNI plugin which does create and set up veths.

We tell people to use this after calling `weave launch`, which will create the bridge, so that part of the premise also bears re-considering.

**Comment by bboreham** [comment]
Closing: it's been a long time since anyone asked about working with an existing bridge.
