### ISSUE TITLE
launching proxy fails with non-default logging driver

### ISSUE THREAD

**Issue by errordeveloper** [weaveworks/weave#1453]
I've tested it on latest CoreOS 808.0.0 (alpha) that ships with Docker 1.8.2 and runs it with `--log-driver=journald` and got this

```
Sep 21 19:08:41 core-01 weave[1357]: The weaveproxy container has died. Consult the logs with 'docker logs weaveproxy' for further details.
```
where `docker logs weaveproxy` says:
```
"logs" command is supported only for "json-file" logging driver (got: journald)
```

**Comment by rade** [comment]
So there are two issues here: 1) the proxy startup (as well as `weave env|config`) depend on `docker log` working, and 2) weave's container death error reporting recommends `docker logs <container>` when this evidently is not guaranteed.

(2) is a usability nightmare. We introduced these very specific instructions precisely because docker newbies didn't know what to do when presented with "consult the container logs". Looks like modern docker has become a lot less newbie friendly, and I am afraid we are going to have to folllow suit :(

I have no idea what to do about (1). Since the proxy runs in the host network namespace we really don't want to make it listen on some fixed port for 'control' messages.

**Comment by paulbellamy** [comment]
We use the logs for two things: a) to wait for the proxy to start, and b) to get back the proxy's listen address.

b) is easy, as we could stash it somewhere else (env var, labels, whatever)
a) is hard, but we could just check the container state, until it's running. But it will slow down weave launch.

**Comment by paulbellamy** [comment]
We could have a fifo (or unix socket, maybe) inside the weaveproxy container, exec in, and check that.

**Comment by rade** [comment]
Note that the proxy doesn't actually fail to start, despite what the message says.
