### ISSUE TITLE
Stall while allocating address for dead container

### ISSUE THREAD

**Issue by bboreham** [weaveworks/weave#1459]
As noted in https://github.com/weaveworks/weave/pull/1426#issuecomment-142312227, if IPAM is waiting for consensus then an allocation request for a container that has already died will stall.

Currently IPAM checks if the container is alive _after_ allocating an IP address, to avoid the leak if we check, then it dies, then we allocate.

**Comment by rade** [comment]
This is fiddly. We cannot simply check the container aliveness before calling `Allocator.Allocate(...)` since that would only narrow the race window but not eliminate it. We need to check after we've added the allocation operation to `Allocator.pendingAllocates`. Which makes the API design awkward - we don't really want `Allocator.Allocate(...)` to have code like `checkAlive && dockerCli != nil && 
dockerCli.IsContainerNotRunning(ident)`.

**Comment by bboreham** [comment]
I don't think there is a race window if you check before and after; the allocate operation will go into the pending list and we will cancel it when we see the "died" event. Allocator serialises everything so there isn't a point where we can miss the event between checking and adding to the pending list.

**Comment by rade** [comment]
> Allocator serialises everything

right, but that means the check needs to happen "inside" the allocator. Performing the check before invoking `Allocator.Allocate(...)` would not accomplish that. Hence we run into the API design issue I pointed out.
