### ISSUE TITLE
`weave status` 'connections between' count is misleading

### ISSUE THREAD

**Issue by awh** [weaveworks/weave#1473]
With two peers:

```
$ weave status

       Version: git-0cf3de454106

       Service: router
      Protocol: weave 1..2
          Name: 6a:7e:6e:d2:5e:17(host1)
    Encryption: disabled
 PeerDiscovery: enabled
       Targets: 0
   Connections: 1 (1 established)
         Peers: 2 (with 2 established connections between them)
```

With three peers:

```
$ weave status

       Version: git-0cf3de454106

       Service: router
      Protocol: weave 1..2
          Name: 56:26:d9:97:69:2e(host1)
    Encryption: disabled
 PeerDiscovery: enabled
       Targets: 0
   Connections: 2 (2 established)
         Peers: 3 (with 6 established connections between them)

```

**Comment by rade** [comment]
how is this wrong?

**Comment by rade** [comment]
perhaps you think the figure is off by a factor of 2? It kinda is but note that the connection between two peers has a state *per peer*. Hence it effectively appears twice in the count. It is also kinda nice that, as things stand, the "between them" count is the sum of all the peer "Connections" counts.

So I don't think there is any mis-counting here, just a possible mis-interpretation. Do you have any suggestions for how to word the output to avoid this?

**Comment by rade** [comment]
if instead of "with x established connections between them" it said "with a total of x established connections", would that avoid the confusion?

**Comment by awh** [comment]
It's counting connection endpoints then, not connections. I don't think that's a very useful thing to display to the user though - their conception of a connection is a bidirectional link between hosts.

**Comment by rade** [comment]
> I don't think that's a very useful thing to display to the user though 

Please propose an alternative.

FWIW, I disagree. Peers have connections. The total number of connections is the sum of connections of of all peers. Also bear in mind that the "Connections" count includes failed and otherwise unestablished connections. These are certainly not "bidirectional links between hosts".

**Comment by dpw** [comment]
The conventional use of the word connection is a two-ended thing.  E.g., from RFC793:
> Each connection is uniquely specified by a pair of sockets identifying its two sides.

We can take some liberty in defining what we mean by terms within the codebase (though I think that tendency should be restrained).  But when it comes to information presented to users, it's better to stick to conventional terms.  The number of connections we present could be those fully connected ones, with a count of failed and otherwise unestablished ones presented separately.

**Comment by rade** [comment]
> The number of connections we present could be those fully connected ones, with a count of failed and otherwise unestablished ones presented separately.

Note that, iirc, the only connection states showing up in "Peers" are "pending" and "established", which always have an associated remote peer. We don't necessarily have a consistent view though, so there are 3x3 possible states for any connection between a pair of peers.

**Comment by dpw** [comment]
> Note that, iirc, the only connection states showing up in "Peers" are "pending" and "established", which always have an associated remote peer. We don't necessarily have a consistent view though, so there are 3x3 possible states for any connection between a pair of peers.

But two counts (one of which represents fully established connections, and one of which represents all other states) would give at least as much information as the present single count, right?

**Comment by rade** [comment]
we presently show three counts. total, pending, established. The latter two are omitted if zero.

**Comment by dpw** [comment]
> we presently show three counts. total, pending, established. The latter two are omitted if zero.

Ok.  Is there any great difficulty reconciling that with a scheme along the lines of the one I suggested?

("incomplete connections" might be better than "pending connections", if it became the case that two incomplete connections could go on to form one established connection.)

**Comment by rade** [comment]
It is also worth noting that the information shown in the "Peers" row is a summary of what is shown with `weave status peers`. The latter shows individual peers and and the connections they have, i.e. there will be one line per connection "end".

**Comment by rade** [comment]
I've [removed](https://github.com/weaveworks/weave/commit/2d753ebf1a7e8f59cb975a961d5ef631f1c1ee8e) the "between them".

**Comment by rade** [comment]
@squaremo was confused by the connection counts too, but on the grounds that two adjacent lines which talk about connections refer to different things, namely connections that this peer has vs connections that all peers have.

He came up with the following suggestion:

- leave `Connections` as is
- change `Peers` to only show the peer count
- change `weave status peers` to just list one peer per line, with peer name and nickname (and maybe the connection counts?)
- add `Topology` to the summary, with counts for "pairs" of connections, i.e. we will have counts for "pending", "half-established" (urgh) and "established". NB: this wouldn't show (local) connections in the connecting, failed and retrying states.
- add `weave status topology` to list all "pairs" of connections; we could use `-x-`, `-->`, `<--`, `<->` to indicate the four possible states (four rather than three because that way we can consistently put the initiating peer first)

I also wonder whether we should call "pairs" of connections something else, e.g. "links".

For the topology info we need to deal with inconsistency in the data. In particular, it is possible that we may only have info on one half of a link. Or that the information we have for each half actually refers to different connections - we could detect that by including the connection UID in the gossip, but I doubt that is worth it).

**Comment by bboreham** [comment]
Nobody has complained further or agreed with this issue in over a year; closing.
