### ISSUE TITLE
NetworkManager possibly interfering with 'weave2' interface name

### ISSUE THREAD

**Issue by rade** [weaveworks/weave#1567]
See https://github.com/jpetazzo/pipework/issues/72#issuecomment-49987944

There was a time when veths needed to be named `veth...` in order to stop NM from interfering with them.

The relevant ubuntu patch [got removed only six weeks ago](http://bazaar.launchpad.net/~network-manager/network-manager/ubuntu/revision/986). The change says "debian/patches: removed a bunch of old patch cruft.".

So I am guessing upstream NetworkManager changed, but it is not clear when. The same commit comment, in referring to another removed patch, states "NM doesn't automatically try to manage any side of veth devices anymore."

Hence we are probably fine with recent NetworkManagers, but I do worry that users might be installing weave on older systems and run into problems. Seems to me it would be prudent to rename the i/f to, say, `vethwe`.

@dpw @awh

**Comment by dpw** [comment]
If only NetworkManager kept its hands off non-physical netdevs, we wouldn't need `weave2` in the first place...

While the naming of `weave2` is not ideal (its existence is not ideal), it (or something also beginning in "weave") still seems to me like the name least likely to cause surprise.  `vethwe` seems less obvious, so I wonder exactly what problem it would be avoiding.

I'm developing under ubuntu 1504, with NetworkManager, and while it does produce annoying announcements about `weave2` coming and going, it doesn't seem to interfere with it (because it sees that it is a veth netdev; in contrast, it will down the `weave` ODP netdev because that is not a veth netdev).

I just tried ubuntu 1204, and I don't see any issue there either.  But that's in a server VM (albeit one with NetworkManager installed), and NM seems oblivious to any netdevs except eth0, so maybe there is some other factor missing.  Is anyone in the team still using 1204 on the desktop, and would be willing to try?  Otherwise I'll install a desktop 1204 VM today.

I guess it would be good to check desktop 1404 too.

I suspect RHEL/centos desktop users are a mythical creature.

**Comment by rade** [comment]
> I guess it would be good to check desktop 1404 too.

That's what i am running. Well, 14.04.1. No problems.

The issue is definitely real though; I saw it at the time I posted that comment. What OS/version I don't remember.

**Comment by dpw** [comment]
> The issue is definitely real though; I saw it at the time I posted that comment.

What was the issue though?  "interference" and "flipping out" (from that pipework issue) is not very specific.  I'm unclear whether it is merely that NM produces a desktop notification when the netdev comes and goes (which I do see), or something worse?

> What OS/version I don't remember.

If you personally saw it, isn't it safe to assume that it was some version of ubuntu?

**Comment by rade** [comment]
>  I'm unclear whether it is merely that NM produces a desktop notification when the netdev comes and goes

I think that's all it was.

>  (which I do see)

You do? I don't.

> If you personally saw it, isn't it safe to assume that it was some version of ubuntu?

Yes.

**Comment by rade** [comment]
> (which I do see)

do you also see that when the interface is named `vethwe`?

**Comment by awh** [comment]
I'd prefer `veth-weave`to `weave2` or `vethwe`

**Comment by rade** [comment]
Make it so.

**Comment by dpw** [comment]
> do you also see that when the interface is named vethwe?

On ubuntu 15.04, yes.

**Comment by dpw** [comment]
I don't see any desktop notifications with 12.04 either.

**Comment by dpw** [comment]
To clarify:

* I never see any notifications with 12.04.
* I always see notifications with 15.04, whether it's `weave2` or `vethwe`.
