### ISSUE TITLE
remove quotes around `eval "$(weave env)"` in docs

### ISSUE THREAD

**Issue by rade** [weaveworks/weave#1596]
Our docs sometimes use `eval $(weave env)` and sometimes `eval "$(weave env)"`. The latter is more correct but also unwieldy. I doubt anybody is going to have spaces in their unix domain socket paths, so we should stick to the former.

**Comment by paulbellamy** [comment]
The reason it was introduced in boot2docker is: http://unix.stackexchange.com/questions/181579/bash-command-substitution-with-multiple-unset-export-commands/181581#181581

Based on that, it seems to be an issue with shell splitting and globbing when processing multiple commands. Since we only every run one `export` command it should be fine in our case.

The concern, is that if we ever need to run multiple commands, people (who have copy-pasted this everywhere in guides/docs/scripts/etc) will need to change it.
