### ISSUE TITLE
RFC: Package router, proxy, and plugin in same container

### ISSUE THREAD

**Issue by awh** [weaveworks/weave#1642]
Original reasons for running the proxy in a separate container:
- Avoid the router having a hard dependency on Docker
- Proxy needed to run in host netns to access Docker TCP port

The situation has now changed - the router already has a dependency on Docker due to the weaveDNS merge, and it also now runs in the host netns due to fast datapath. I therefore propose that we distribute the two in the same container image (exact implementation TBD) to obtain the following benefits:
- Simplified `weave` script - in particular `weave launch` and `weave stop` won't have to deal with edge cases around making start/stop of multiple containers appear to be an atomic step
- `weave status` and `weave report` can include proxy related information (inclusion of proxy at bottom of `weave status` is currently implemented via bash script hackery)
- Elimination of races e.g. #1556 

I suspect this may a) be contentious and b) have downsides I haven't thought of - the purpose of this issue is to act as a vehicle for discovery and documentation. Comments please.

**Comment by rade** [comment]
It is not clear what you are proposing here...

- a single image?
- a single container?
- a single process?

> the router already has a dependency on Docker due to the weaveDNS merge

By dependency, do you mean "it references the go-dockerclient package"? Or "it depends on interaction with docker in order to work"? The latter is not the case. You can start the router w/o giving it access to docker, and weaveDNS will work just fine; the lifecycle of entries can be managed through the HTTP API.

**Comment by awh** [comment]
> By dependency, do you mean "it references the go-dockerclient package"? Or "it depends on interaction with docker in order to work"? The latter is not the case.

Without Docker, the feature in weaveDNS that depends on Docker is quiescent; without Docker, the proxy would be quiescent too.

> It is not clear what you are proposing here... 

I am proposing a single process, with internal modularity so that we have the option to produce images with different feature sets in future if we need to.

**Comment by dpw** [comment]
> I am proposing a single process

This has a downside:  A panic in one component will take out the whole process.

**Comment by squaremo** [comment]
Last time I looked, the API proxy doesn't need the router to be running to operate, and vice versa. This means they can be started and restarted independently. Does this matter for users? Less so if the single binary can be run in router-only and proxy-only modes, I suppose.

One other consequence I can think of is that it will reduce the need for exposing stable APIs to the router, since it can be done internally, and these will get less attention. That could be detrimental for anything that wants to drive the router/IPAM/DNS in a way not covered by the weave script.

**Comment by rade** [comment]
> the API proxy doesn't need the router to be running to operate, and vice versa

The router certainly doesn't need the proxy. But the proxy does need the router to operate usefully. Though, iirc, start order doesn't matter.

**Comment by rade** [comment]
Having the separate components is detrimental to the user experience, since users never quite know exactly what the components do, how they interact and what their dependencies are.

**Comment by philwinder** [comment]
+1 but this is a larger problem that simply merging the docker containers. It's the UX that is the most important. Not how it is technically achieved. E.g. talking about a router and a proxy and a plugin is more detrimental to the UX than the technicalities of running them as separate containers. It should be "the weave product". The user shouldn't have to figure out whether he needs to use the proxy or the plugin.

**Comment by rade** [comment]
> It's the UX that is the most important. Not how it is technically achieved.

Understood. But the UX is constrained by the implementation; it's impossible to make the latter not leak into the former.

**Comment by rade** [comment]
> The user shouldn't have to figure out whether he needs to use the proxy or the plugin.

On that point, I am afraid, we are stuck. There *are* multiple ways weave interacts with docker; which one is best depends on the user's situation. We can explain the criteria, but the choice doesn't go away.

**Comment by bboreham** [comment]
Note that the plugin process was merged into the router in #2727, because Docker Store rules forbade running two processes and a process manager to watch over them.
