### ISSUE TITLE
Event based notification API for name updates

### ISSUE THREAD

**Issue by awh** [weaveworks/weave#1645]
Provide a method for clients to receive timely updates of (de)registrations so they can avoid polling and TTLs.

**Comment by rade** [comment]
Do we expect this feature to be available to application containers?

I think that would be fine conceptually from a security POV - anything you can learn via the event stream you can already discover through A and RR queries.

But it does complicate implementation since a) we'd somehow have to make the event stream endpoint accessible to containers, and b) do so w/o also enabling access to the weave control port.

**Comment by bboreham** [comment]
Is this the same as #1591?

**Comment by awh** [comment]
Dup sorry!
