### ISSUE TITLE
Authenticated peering

### ISSUE THREAD

**Issue by psi-4ward** [weaveworks/weave#1649]
It would be nice to let only authenticated Peers connect to the network without using full encryption.
Perhaps with a PSK.

Use-Case:
I have several Servers in the same data-center. Traffic between servers gets routed internally but every server has only one public ip and is accessible from the internet.

**Comment by rade** [comment]
> every server has only one public ip and is accessible from the internet.

Presumably they are all part of some subnet - how else would the DC network know that they should be routed internally?

In which case, why not simply put some firewall rules in place to only allow access to the weave ports from that subnet?

(OP says "yes exactly. as i said this is not a big problem and ill solve it with some iptable restrictions")

Implementation-wise, we'd need to sign both the control and data traffic, since otherwise unauthenticated users could inject traffic.

**Comment by bboreham** [comment]
@psi-4ward I believe that #1758, released in Weave Net 1.4.0, will give you what you are asking for: supplying `--password` forces authentication but `--trusted-subnets` enables unencrypted links on specific subnets.

If you want every peer to use unencrypted links then you can specify `--trusted-subnets=0.0.0.0/0`
