### ISSUE TITLE
Add option to stop weave adding a multicast route

### ISSUE THREAD

**Issue by bboreham** [weaveworks/weave#1741]
For users that are happy with the default routing of multicast packets, weave adding a route to `224.0.0.0/4` is unhelpful.  We could have yet another environment variable to turn off this behaviour.

**Comment by rade** [comment]
> For users that are happy with the default routing of multicast packets

What are those users using the default multicast route for?

**Comment by Lawouach** [comment]
There is no default multicast route actually. With this being said, my setup involves multicasting video streams through the docker bridged network because it suits my infrastructure. I'm keeping weave for multi host management only. The weave default multicast route breaks that setup.

**Comment by Lawouach** [comment]
Actually, thinking again about it, I may have found a way to actually plug my underlying setup to the weave bridge instead of the docker bridge. In that case, I have a feeling I could simply benefit from the weave default multicast route indeed. I'll try it out tomorrow and report back.

**Comment by Lawouach** [comment]
Hi all,

I have indeed managed to get my setup running over weave's network, including the multicast traffic.

With that said:

* There are various tickets opened to let multicast being handled by the overlay network directly over at libnetwork: https://github.com/docker/libnetwork/issues/552. I'm wondering if that route may not eventually interfere.
* unless I'm mistaken, the weave network doesn't propagare IGMP memberships outside its network. For instance, I have a video source streaming on my network somewhere. Currently, I have to enslave one physical interface to the docker bridge so that the IGMP carrier from the physical switch sees the membership. Unfortunately, I cannot enslave a physical port to the weave bridge AFAIK to keep the same behavior. I therefore still need to remove the route from ethwe when the app need to register to a multicast source outside the weave bridge.

**Comment by Lawouach** [comment]
Well thank you guys for this! :)

**Comment by awh** [comment]
@Lawouach Happy holidays :)
