### ISSUE TITLE
improve check for "container running"

### ISSUE THREAD

**Issue by bboreham** [weaveworks/weave#1778]
If a container is restarting, `State.Running` is still `true`.

    $ docker inspect --format='{{json .State}}' weaveplugin
    {"Status":"restarting","Running":true,"Paused":false,"Restarting":true,"OOMKilled":false,"Dead":false,"Pid":0,"ExitCode":2,"Error":"","StartedAt":"2015-12-11T16:30:57.160366578Z","FinishedAt":"2015-12-11T16:30:57.190084967Z"}

so the code in the weave script which examines `State.Running` needs to be amended.

For a container with a restart policy, we could make `check_not_running` rm the restarting container, so:

    weave launch-plugin --foo

creates an infinite restart loop because the argument is unrecognized, but a subsequent

    weave launch-plugin [some-other-args]

rm's the restarting one and starts the new one you asked for.

**Comment by rade** [comment]
11:07:54) matthias: surely a container that is in a restart loop will alternate between "running" and "restarting".
(11:08:46) bryan: Yes, that is true for State.State, but State.Running will remain true throughout.
(11:09:17) matthias: yes, but with the proposed change the behaviour is down to chance.
(11:09:39) matthias: i.e. if you catch the container in "restarting" it will be killed, otherwise it won't.
(11:10:31) bryan: That behaviour seems correct given all the available evidence at the time.
(11:10:53) bryan: We cannot predict whether it is about to restart.
(11:11:26) bryan: Given that Docker adds an increasing delay, your chances of hitting the right moment get better.
(11:11:51) matthias: good luck writing an automated script for that.
(11:13:18) bryan: Maybe just print a message saying it is restarting and instructing the user to do stop if they want to.
(11:13:59) matthias: i.e. how would you go about writing a script that "ensures the plugin is started, and not in a restart loop"?
(11:14:27) matthias: right. message might be better.
(11:14:46) matthias: essentially it's in a limbo state.
(11:14:53) bryan: This issue isn't about "ensure it is started"; it's about not passing on a confusing message from Docker.
(11:15:14) bryan: The sequence I had in mind was:
(11:15:27) bryan: weave launch-plugin --incorrectly-spelled-option
(11:15:32) bryan: "fuck"
(11:15:45) bryan: weave launch-plugin --correctly-spelled-option
(11:15:50) bryan: weave is already running
(11:15:56) bryan: "No it isn't!"
(11:16:36) matthias: yes, but the trouble is you can still get that message, even with your change.
(11:16:58) bryan: yes; I think I'll change it.  thanks!
(11:17:39) matthias: but why do anything?
(11:17:54) bryan: because the message is wrong; it isn't running
(11:18:08) matthias: is it not? how do you know?
(11:18:31) bryan: because it exits immediately on an incorrectly-spelled option
(11:19:15) bryan: the log file gets bigger and bigger while the user figures out what to do
(11:20:06) matthias: even if we just have a different message, it can still report "already running". It's still down to chance.
(11:20:34) bryan: I know, but in the 98% case that it is restarting, the user will be better-off.
(11:20:50) bryan: And in the 2% case that you catch it, technically it was running, so we're not lying.
(11:21:02) matthias: ok. and they can stop it with "weave stop-plugin", restarting or not, right?
(11:21:07) bryan: yes
