### ISSUE TITLE
Some deprecation warnings are fatal

### ISSUE THREAD

**Issue by bboreham** [weaveworks/weave#1811]
I found it odd that the script says "Warning" when the next thing that happens is the container rejects the option and dies.

```
$ weave launch-proxy -no-default-ipam
Warning: -no-default-ipam is deprecated; please use --no-default-ipalloc
The weaveproxy container has died. Consult the container logs for further details.
$ docker logs weaveproxy
flag provided but not defined: -no-default-ipam
See '/home/weave/weaveproxy --help'.
```

It looks like this specific case is the only one in `prog/weaveproxy/main.go`, but we should have a look round for others.

**Comment by rade** [comment]
There is a related issue that I could swear we discussed before but cannot find...

The weave script has a single deprecation warning function, which has no awareness of whether the option in question is router or proxy option. So in some cases it will issue warning and then the container will die simply because the supplied option is a deprecated router (or proxy) option but we were launching the proxy (or router).

**Comment by bboreham** [comment]
We removed all the deprecated options in 2.0
