### ISSUE TITLE
use case question

### ISSUE THREAD

**Issue by joeblew99** [weaveworks/weave#1834]
i have about 100 sites, with maybe 3 or 4 servers in each.
they run coreOS and ubuntu.
they are DHCP booted.
the wan router is locked down, but with the standard tcp 80 and 443 open.

I was wondring if weave can help me to be able to join them to our cloud ?

I guess weave would need to do some NAT punchthrough ? I could ask the network admin to pen some pots for me at each site also.

some sites have a static public IP, but some have a dynamic ip that changes sometimes.

**Comment by rade** [comment]
You'll need to [open a couple of ports](http://docs.weave.works/weave/latest_release/features.html#multi-cloud-networking). Weave does a reasonable job of traversing NATing firewalls.

> some sites have a static public IP, but some have a dynamic ip that changes sometimes.

As long as there are *some* static IPs then weave should be fine. You'd tell all peers to connect to those static IPs, which in itself is enough to establish a working weave network, due to weave's [multi-hop routing](http://docs.weave.works/weave/latest_release/features.html#multi-hop-routing), plus weave's [built-in discovery](http://docs.weave.works/weave/latest_release/features.html#dynamic-topologies) will automatically attempt to establish direct connections between all peers.

PS: [weave-users](https://groups.google.com/a/weave.works/forum/#!forum/weave-users) is probably a better place for this kind of question.

**Comment by joeblew99** [comment]
Thanks.

I will close and ask in the group
