### ISSUE TITLE
document `--no-multicast-route`

### ISSUE THREAD

**Issue by rade** [weaveworks/weave#1835]
#1755 failed to document the newly introduced `--no-multicast-route` flag. The two other flags resembling it most most closely - `--no-rewrite-hosts` and `--without-dns` - are both documented.

Documentation should include a clue as to why one may want to use the flag.

**Comment by Lawouach** [comment]
My point  in #1755 was that you usually invite users to start weave services via ``weave launch``, not the individual sub-commands like ``weave launch-proxy``. It appears that ``--no-multicast-route`` isn't populated to the proxy when calling the high-level ``weave launch`` command, unless I'm mistaken.

That's fine I guess but then, maybe the systemd doc page should be updated so that it provides examples with units for each weave service. Currently, the documentation almost always tell the user to go with ``weave launch`` only. Either ``weave launch`` is the the main entry point and should probably accept all available parameters, or it should be clearer when to call each subsystem.

**Comment by rade** [comment]
From [the proxy setup docs](http://docs.weave.works/weave/latest_release/proxy.html#setup)
> The `weave launch` form is more convenient, however you can only pass proxy related configuration arguments to `launch-proxy` so if you need to modify the default behaviour you will have to use the latter.

**Comment by Lawouach** [comment]
Hi rade,

You are right indeed. Mind you, I couldn't find how to get to that page from the doc, is it linked from the main doc? 

I'm also confused why ``weave launch`` filters parameters for the proxy and plugin but not for the router. I couldn't find a page dedicated to the router that documents the specifics.

Anyway, thanks for documenting the multicast flag indeed. I'll know where to link people to.

**Comment by rade** [comment]
>  I couldn't find how to get to that page from the doc, is it linked from the main doc? 

[Yes](http://docs.weave.works/weave/latest_release/features.html#docker).

> I'm also confused why `weave launch` filters parameters for the proxy and plugin but not for the router

`weave launch` does no filtering. It simply passes all parameters to `weave launch-router`.

**Comment by Lawouach** [comment]
> weave launch does no filtering. It simply passes all parameters to weave launch-router.

I wasn't clear. It does pass all parameters to launch-router but not to the other two (plugin, proxy). I wouldn't have expected that. What makes router special in this case?

> Yes

Indeed. Though, the link contrast is rather unhelpful I guess. Fair enough.

**Comment by rade** [comment]
>  It does pass all parameters to launch-router but not to the other two (plugin, proxy). I wouldn't have expected that.

That wouldn't work. The proxy and plugin would trip over any router parameters, since they don't understand them.

**Comment by Lawouach** [comment]
I gathered as much since passing the proxy parameters to ``weave launch`` got everything to collapse conversely :)

I was simply stating that I was surprised as I would have expected the weave script to sort parameters out before it passed them to each program. Afterall, it does go through them to lookup common parameters anyway. That went against my naive expectation that launch was a transparent proxy for all services, a rather dull shortcut indeed.

I'll update my scripts acconrdingly so that I can properly configure them. I will also make sure I am more careful when reading the documentation in the future ;)

Cheers for the explanation.

**Comment by rade** [comment]
> I would have expected the weave script to sort parameters out before it passed them to each program.

That would require the script to know about all parameters. Which is distasteful, since that would end up duplicating information, and potentially get out of sync.

> Afterall, it does go through them to lookup common parameters anyway.

There is only one common parameter.

> That went against my naive expectation that launch was a transparent proxy for all services, a rather dull shortcut indeed.

`weave launch ARGS` *is* a rather dull shortcut. For `weave launch-router ARGS && weave launch-proxy && weave launch-plugin` :)

What you are expecting is more like `weave $(complain-about-unknown-args ARGS) && weave launch-router $(weave extract-router-args ARGS) && weave launch-proxy $(weave extract-proxy-args ARGS) && weave launch-plugin $(weave extract-plugin-args ARGS)`. #1838

**Comment by Lawouach** [comment]
Ah ah. Indeed.

Much agreed overall. Thanks!

**Comment by bboreham** [comment]
Fixed in 4b0fe502f033cf41eed885db1d9f74ae0016abd1

**Comment by rade** [comment]
> Fixed in 4b0fe50

This hadn't been merged into 1.4 and master. Done now.
