### ISSUE TITLE
plugin prevents successful `weave launch` on reboot

### ISSUE THREAD

**Issue by rade** [weaveworks/weave#1869]
The plugin is started with a restart policy of `always`. Consequently, if you have a startup script that runs `weave launch`, such as our published [systemd](http://docs.weave.works/weave/latest_release/systemd.html), it will fail the 2nd time round, since `weave launch` will report `weaveplugin is already running; you can stop it with 'weave stop-plugin'.` and exit with status 1.

**Comment by bboreham** [comment]
If there was a `$WEAVEPLUGIN_DOCKER_ARGS`, then folks who didn't want the restart policy could put `--restart=none` there.

**Comment by bboreham** [comment]
Although that may not work work if you actually use the plugin; I've seen Docker get stuck trying to talk to the plugin before starting to accept commands.

**Comment by DanielDent** [comment]
In a configuration I've been building, I've gone with 4 systemd unit files, plus an environment file, which I've attached.

These files might be helpful for #1836 too.

The only problem with this arrangement is that the weave-plugin service doesn't start cleanly on a reboot because launch-plugin exits uncleanly. Perhaps a "--ifnotlaunched" or similar flag could be made available so that the weave script returns 0 if the plugin is already running.

[weave-config.txt](https://github.com/weaveworks/weave/files/85700/weave-config.txt)
[weave-proxy.service.txt](https://github.com/weaveworks/weave/files/85702/weave-proxy.service.txt)
[weave-expose.service.txt](https://github.com/weaveworks/weave/files/85704/weave-expose.service.txt)
[weave-plugin.service.txt](https://github.com/weaveworks/weave/files/85703/weave-plugin.service.txt)
[weave-router.service.txt](https://github.com/weaveworks/weave/files/85701/weave-router.service.txt)

**Comment by awh** [comment]
Fixed by b3a29bec1b98aca7bdd0a987e4e4e4909f7d8fb0
