### ISSUE TITLE
default init-peer-count is off-by-one when launch args include self

### ISSUE THREAD

**Issue by errordeveloper** [weaveworks/weave#1881]
We currently presume that if only one peer is passed to `weave launch`, that this peer won't be itself.

When automating provisioning, It is often convenient to write less logic possible and just pass a list of all know peers, which works just fine except for the case when this length of this list is 1.

There exists logic to prevent connection to itself, it shouldn't be impossible to correct IPAM expectations on the basis of [`ErrConnectToSelf`](https://github.com/weaveworks/weave/search?utf8=%E2%9C%93&q=ErrConnectToSelf&type=Code), given only one peer is expected.

**Comment by rade** [comment]
Sure it's possible, but it is completely hideous to implement.

- init-peer-count can be set explicitly; to implement this feature we need to remember whether that was done, or the init-peer-count was derived from the arg count, since we only want to "correct" it in the latter case
- the list of destinations to connect to changes dynamically - both through `weave connect|disconnect` and peer discovery; to implement this feature we need to remember what the original launch arguments are, so that when we do detect that we have connected to ourself, we only "correct" the init-peer-count if the destination address was in the original launch args.
- we must perform the correction once only. somehow.

There are probably others.

Seems to me that by far the easiest and reliable way to fix this issue is for the user to set `--init-peer-count` to the length of args minus one. After all, they (usually) know when they are feeding the peer's own address into that.

**Comment by bboreham** [comment]
I think if #1721 were implemented then the desired semantics would fall out.

**Comment by rade** [comment]
> I think if #1721 were implemented then the desired semantics would fall out.

I don't see how that addresses any of the points I raised.

**Comment by bboreham** [comment]
> I don't see how that addresses any of the points I raised.

- It says to do it only in the absence of a specified count.
- It says to pick the count at the time of consensus, which addresses the issue of dynamic changing and performing it only once.

**Comment by rade** [comment]
I see. How would we ensure that consensus is only initiated after we have (potentially) connected to ourself and discovered that we should exclude that IP from the init-peer-count calculation?

**Comment by bboreham** [comment]
> ensure that consensus is only initiated after 

That is harder.

**Comment by awh** [comment]
Closed by #2070.

**Comment by bboreham** [comment]
#2070 was incorrect, sadly.  See https://github.com/weaveworks/mesh/pull/57

**Comment by bboreham** [comment]
Filed #2481 to cover
