### ISSUE TITLE
Docker's "--restart=always" missing from weaveproxy and weave

### ISSUE THREAD

**Issue by ventz** [weaveworks/weave#1904]
Hi,

I noticed that the "weaveplugin" container is the only that has a "--restart=always" policy.

Could you please add "--restart=always" to the docker run for:
* weaveproxy
and
* weave

so that the mesh will auto-start on host reboots?

This would be in "launch_proxy()

**Comment by bboreham** [comment]
Hi @ventz, and thank you for your interest.

We added the `--restart=always` on the plugin to try to fix a particular problem: if it isn't running when Docker tries to talk to it, then Docker can hang for a long time, and it that hang happens at startup then `systemd` can time out and leave you with no Docker at all.  (It turns out `--restart` didn't really fix the problem, but that's [a separate issue](https://github.com/weaveworks/weave/issues/1907))

The weave router needs a number of configuration steps before it can operate at startup; #1518 added support for running those under restart policy, but there were a number of unexpected outcomes.  The most recent fix was in #1561, just 11 days ago.

I mention all this to justify that we have [always advised](http://docs.weave.works/weave/latest_release/troubleshooting.html#reboots) users to launch Weave from their process manager (e.g. `init` or `systemd`).  We can't simply reverse the default as you suggest; it would need to be an option.

However, the environment variables `$WEAVE_DOCKER_ARGS` and `$WEAVEPROXY_DOCKER_ARGS` exist to allow this kind of tweaking, so please go ahead and use those and let us know how it goes.

Lastly, could I just check the motivation for wanting to use Docker restart policy instead of an init script?  It seems you would have to run that script once, anyway, to ensure your machine was in a predictable state when you built it.  What is your use-case?

**Comment by rade** [comment]
> We can't simply reverse the default as you suggest; it would need to be an option.

#1859 should address that.

**Comment by ventz** [comment]
@bboreham - Thank you for the incredibly detailed response.

I had not seen the /troubleshooting.html#reboots section, but I actually ended up doing the same thing for the time being (specifically, with just /etc/rc.local because of our use case).

Our use case is a little bit different than your typical setup -- we end up using cheap instances (ex: with AWS spot instances) to create "semi-temporary" on-demand docker hosts and mesh them, in order to create N-node clusters for a scientific database. The problem is that we don't have the information ahead of time.

This means that we launch weave on the first node, and every next node adds the previous IP(s). Some deploys have 10+ IPs, some have 200+, and others 1000+. After the inital docker setup, we tend to update/upgrade the system packages, and then update grub (GRUB_CMDLINE_LINUX="cgroup_enable=memory swapaccount=1") and then reboot so that the kernel changes can take place. This is one place where the reboots cause issues, but you can argue that we should deploy weave AFTER the system comes back up. The main issue is really when a planned or unplanned reboot happens.

As you/the docs mention, you can use your favorite process manager to take care of that. For us, it's a bit easier just to place an entry in /etc/rc.local with the CLI command with the correct arguments (mainly, the dynamically generated IPs, trusted subnets, passwords, etc).

This works perfectly fine, it's just not elegant. It would be nice to have weave come back up on a system reboot in the same state that it was in before the reboot. After reading a bit more, and through the weave code, I understand why this is not currently possible.

**Comment by bboreham** [comment]
Just to be clear, if you set `$WEAVE_DOCKER_ARGS` and `$WEAVEPROXY_DOCKER_ARGS` to `--restart=always` on first launch, then the processes would all come back.

Also, remember to set `--init-peer-count` high enough that they don't form cliques on restart.
