### ISSUE TITLE
Stale WeaveDNS entries

### ISSUE THREAD

**Issue by bboreham** [weaveworks/weave#2023]
As reported at https://github.com/weaveworks/weave/issues/1976#issuecomment-192985795

**Comment by rade** [comment]
One possible reason is #1867. But let's assume we don't hit that...

Say we have a container C on peer X. Now somebody stops X, removes C, and restarts X.

Another peer Y might see the following event stream

- removal of peer X from topology -> Y removes DNS entry for C
- addition of peer X to the topology
- DNS entry for C@X, sent by some other peer as part of regular gossip before that peer had seen the removal of A from the topology.

Note that both #1867 and this issue have one thing in common: a peer that restarts quite quickly. There should be evidence in the logs for that.

**Comment by rade** [comment]
Note that the probability of #1867 or this one occurring rises with the number nodes since it only takes one peer in the network to fail to remove a DNS entries (as in #1867) or re-create it accidentally, as per this issue, for the rest of the peers to become equally contaminated, thanks to gossip & eventual consistency semantics.

**Comment by rade** [comment]
Possible fix: replace the entry PeerName with PeerUID and maintain the following invariant: for a DNS entry to exist, it must belong to a peer with a PeerUID that is present in the topology.

**Comment by rade** [comment]
@bboreham has just proposed an alternative fix: get peers to tombstone entries which they receive and that purport to belong to them but for which they haven't actually got a record.

This means we wouldn't have to change the entry format.

Alas there is a problem. We have no idea what the last version of the entry was. Just because we received an entry from one node doesn't mean another node doesn't hold a higher version of that same entry.

**Comment by bboreham** [comment]
But we would subsequently receive that higher version, and again send out a higher update to contradict it.

**Comment by rade** [comment]
it is fundamental for convergence to maintain the invariant that no two entries must exist which have the same version but are different.
