### ISSUE TITLE
Need Clarification on manual ip allocation and automatic ip allocation by IPAM

### ISSUE THREAD

**Issue by rachit1arora** [weaveworks/weave#2082]
I need clarification what should be the range given while launching weave inorder to avoid clashes between manual ip allocation vs automatic. In our requirement we always want to do manual ip allocation . 

As of now we just used to to weave launch --ipalloc-range 172.16.0.0/16 host1
And we see in docker logs weave following error 
ERRO: 2016/03/22 04:36:35.800423 [allocator] address 172.16.16.5 is owned by other peer 

We also see error like following 
**ERRO: 2016/03/22 02:59:56.301376 [allocator] Claim request for 6bbf61038b87ac3b256b81a191f1fe761fed8ddf55d42643405ffbc8673f495c cancelled**
WARN: 2016/03/22 03:02:03.697686 [allocator]: Unable to claim: address 172.16.16.5 is owned by other peer 0e:20:72:7c:48:
INFO: 2016/03/22 03:02:05.795888 Discovered local MAC 16:22:1d:26:5a:7f
INFO: 2016/03/22 03:02:06.198459 [nameserver 3e:06:b1:cd:03:67] Ignoring registration dn03.se***. 172.16.16.5 0e67dafd281474754c174e700f8baf54f866c427739544529c455e420bb5dd18 (not a subdomain of weave.local.)
INFO: 2016/03/22 03:02:06.789601 Discovered remote MAC 3e:f2:4f:1b:b5:6a at a6:a5:d3:40:6b:
INFO: 2016/03/22 03:02:06.790572 Discovered remote MAC 46:7a:15:3c:a5:c1 at e2:b2:c8:63:37:
**ERRO: 2016/03/22 03:02:07.901193 [allocator] address 172.16.16.5 is owned by other peer **0e:20:72:7c:48:

Questions
1.  WHat happen to the container who is assigned this ip manualy and there is a clash with the automatic ip allocator ? Will it work normally ? 
2. How we can avoid these clashes 

I looked into various issues surrounding this , but could not find exact answer . Please clarify

**Comment by awh** [comment]
The way you have things configured right now, as long as you're _always_ specifying addresses manually (e.g. as a CIDR argument to `weave run` or with `docker run -e WEAVE_CIDR`), weave's IPAM will simply track what you're doing and warn you if you try to use the same address more than once - even on different peers. That's why you're getting this message:

```
Unable to claim: address 172.16.16.5 is owned by other peer 0e:20:72:7c:48:
```

This is not a clash between an automatic allocation and a manual allocation (you said you were always doing manual allocation remember) - weave is telling you that _you_ already specified that address manually for a different container, in this case on another peer `0e:20:72:7c:48:`

If you don't want weave to track addresses in this fashion, you disable IPAM completely:

```
weave launch --ipalloc-range=""
```

**Comment by rachit1arora** [comment]
Thanks for the clarification

**Comment by awh** [comment]
> Thanks for the clarification

You're welcome!
