### ISSUE TITLE
[w|W]eave[dns|DNS| DNS] naming zoo

### ISSUE THREAD

**Issue by rade** [weaveworks/weave#2102]
Looks like we have collected all the animals in the weavedns naming zoo.

| Name | 1.4 count | master count |
| --- | --- | --- |
| weaveDNS | 39 | 12 |
| WeaveDNS | 8 | 3 |
| Weave DNS | 1 | 2 |
| weavedns | 9(*) | 43 |
| Weavedns | 0 | 8 |

(discovered by running `(cd site; find . -name "*.md" -exec grep "<name>" {} \; | wc -l)`)

(*) these are all just references to `weavedns.html`, which is fine.

There used to be a method here: The component is called `weaveDNS`, except when it appears at the beginning of a sentence, in which case it is called `WeaveDNS`.

This has been lost in the recent doc changes.

cc @abuehrle

**Comment by abuehrle** [comment]
I did change this to lower-case since that's what we agreed on months ago.  For the record, I do think it looks better with the DNS in upper case. 

BTW: This feels a bit like a scene out of that movie Brazil, but this edict is lifted from the "Weaveworks Content Style and Voice Guidelines" which was produced months ago.  

In our guidelines, quoted here, we decided: 

> Features are not components.

> There are other sub-components of Weave such as DNS. We do not elevate features into components. Refer to them as a feature of the product when you need to refer to them vs. specifically named entities. For example, “The DNS server in Weave Net”. Do not create new features with standalone names like “Weave DNS”. You might say “Weave’s DNS server works by …” rather than “Weave DNS works by…”

"
and 

> "**Products vs. Services**
> Product names are always capitalized, but only if the word is a part of the official product.  To avoid confusion, how the product is deployed or sold is not capitalized.  
> 
> **Incorrect**: Weave Scope Cloud Service
> **Correct:** Weave Scope cloud service
> 
> **Incorrect:** WeaveDNS
> **Correct:** weavedns is a library / feature

> All product names and network services or libraries should be offset in bold within a document. 
> You could also call it a network service if you don't want to talk about libs or features.

Complaints to the contrary should be forwarded to the appropriate party :)

However, it looks like I've missed a few, so a search and replace with whatever we decide should be done, I suppose.
