### ISSUE TITLE
make it more obvious that clocks need to be in sync between peers.

### ISSUE THREAD

**Issue by brb** [weaveworks/weave#2174]
In [nameserver][1] we assume that clocks of peers are synchronized.

In order to make users aware of it, we should document the assumption.
 
[1]: https://github.com/weaveworks/weave/blob/88e2761b185fb8f881414a9084be255387419658/nameserver/nameserver.go#L201

**Comment by rade** [comment]
Nobody reads documentation. The only time users will become aware of clock synchronisation being an issue is when they encounter that message. Which they never might because... nobody looks at the logs.

So IMO to really make a difference here we should add some information to `weave status`. Except this info so rarely needed, that this seems overkill.

PS: I am aware of exactly one user who ran into problems due to out-of-sync clocks.

**Comment by rade** [comment]
>  Which they never might because... nobody looks at the logs.

Actually, iirc the error ends up causing a connection shut-down and hence pops up in `weave status connections`.

I am totally fine with adding the clock sync requirement to our docs, I just don't think it will make much of a difference.

**Comment by rade** [comment]
> I am totally fine with adding the clock sync requirement to our docs

On reflection, I think this will do more harm than good. For the requirement to be noticed it would have to appear in the start instructions. Which is really distracting, given that in the vast majority of installations this is simply not something the user needs to care about.

So instead I think we should improve the error message, so that it is clearer what the problem is.

> Actually, iirc the error ends up causing a connection shut-down and hence pops up in `weave status` connections.

That depends on which side detects the error. If the error is detected by the accepting end, then it appears in the logs only.
