### ISSUE TITLE
Peer list persistence

### ISSUE THREAD

**Issue by awh** [weaveworks/weave#2186]
Following up #2172, my thoughts on how peer list persistence should work from the user's perspective:

### First interactive `weave launch`

Use supplied peer list. Rationale: it's the only possibility.

### Router restarted by Docker

Use peer list supplied by Docker from immutable container state + any intervening connect/forget. Rationale: if Docker restarts for me it's because something unexpected happened, so it's reasonable for it to restore the summation of my interactive commands up to this point.

### Subsequent interactive `weave launch`

Use supplied peer list only - intervening connect/forget are ignored. Rationale - I must have stopped weave manually, and will have an expectation that what I specify now is obeyed.

### Router started by systemd (--no-restart)

Use supplied peer list only - intervening connect/forget are ignored. Rationale - I expect this to be used in automated provisionings where the 'resilience on reboot' requirement is fulfilled by distributing a systemd environment file with an updated peer list.

**Comment by awh** [comment]
We can distinguish the initial interactive `weave launch` from being restarted by Docker by using a sentinel file inside the router container:

```
if sentinel file exists inside router container:
    use CLI list modulo persisted connect/forget from data volume
else
    purge persisted connect/forget from data volume
    touch sentinel file
    use CLI list
fi

```

`weave stop` would need to remove the sentinel file so that the next `weave launch` ignore previous connect/forget as described above.

**Comment by awh** [comment]
Note that because upgrades require `weave stop` + `weave start`, it is implicit in this solution that connect/forget do not persist across upgrades. We could have a dedicated upgrade command that does the right thing, e.g. upgrading the container image and touching the sentinel file inside so that any persisted connect/forget information in the data volume are observed.

**Comment by awh** [comment]
We might also want a way for the user to access the docker restart behaviour manually e.g. `weave relaunch` or `weave launch --resume` that do not allow the specification of CLI peers (they are read from the immutable container metadata)

**Comment by rade** [comment]
The main purpose of dynamic peer list management is to a) connect to newly added peers which cannot reach existing peers due to firewalls, and b) forget peers that have been removed, so we don't keep attempting to connect to them. Crucially, `weave connect|forget` enabled this to be done *without restarting the router* - otherwise simply stopping the router and starting it with an amended peer list would suffice.

What is our recommendation for how this should be handled in a systemd-managed cluster? i.e. how should one go about adding/removing peers *without restarting the remaining routers*?
