### ISSUE TITLE
register DNS for rkt containers

### ISSUE THREAD

**Issue by errordeveloper** [weaveworks/weave#2226]
This would probably involve metadata service, but there is no obvious way of setting name/hostname of a container, nor there is any notion of tags. Would be great to get some better understanding of this.

**Comment by alban** [comment]
You can set the hostname with `rkt run --hostname=...`:
```
      --hostname=""		pod's hostname. If empty, it will be "rkt-$PODUUID"
```

About tags, can you give an example how you would use them?

**Comment by alban** [comment]
About DNS: rkt does not start a DNS server but you can configure the container's `/etc/resolv.conf` with the following command line parameters:
```
      --dns=			name servers to write in /etc/resolv.conf
      --dns-opt=		DNS options to write in /etc/resolv.conf
      --dns-search=		DNS search domains to write in /etc/resolv.conf
```

Is it enough for your use case, or do you need more?

There is a pending issue about getting the DNS information from the CNI plugin instead of the rkt command line parameters but it is not implemented yet: https://github.com/coreos/rkt/issues/2044
If it would be useful for Weave, please say so on the issue above ;)

**Comment by errordeveloper** [comment]
@alban ok, so `--hostname` wasn't documented where I looked (https://github.com/coreos/rkt/pull/2519). It should sufficient.

**Comment by steveeJ** [comment]
@errordeveloper 
Is there still the need for a new feature in rkt or is `--hostname` sufficient for your use-case?
