### ISSUE TITLE
weave forget [peers] didnot work when two peers have established connections.

### ISSUE THREAD

**Issue by elianka** [weaveworks/weave#2272]
i have use "weave connect peerB" on peerA, and connection established.
then i use "weave forget peerB" on peerA, the connection still there, is it right?

weave script 1.5.0
weave router 1.5.0
OS: centos-7 kerenel: 3.10.0-229.4.2.el7.x86_64

**Comment by rade** [comment]
The command is called `forget`, not `disconnect`, for a reason. The [docs](https://www.weave.works/docs/net/latest/using-weave/finding-adding-hosts-dynamically/) say that it
> prevents the peer from trying to reconnect to that host *once connectivity to it is lost*

Is there a specific reason for you wanting to force a disconnection?

**Comment by elianka** [comment]
Thanks for your reply. 
yes, i want to disconnect a peer manually, and i think its a reasonable operation when i don't want to connect to a peer.
i cannot find a option to do that, and weave connect is along with weave forget, so i try it.

**Comment by rade** [comment]
Please elaborate on what you are trying to achieve. If you want to remove a peer from a weave network, then simply stop it. And *then* run `weave forget` on any peers on which you previously ran `weave connect`.

In general, connections between peers can be established in either direction, and peers discover others automatically. Therefore when telling peer A to disconnect from B peer, it is quite likely that peer B would immediately establish a connection the other way, or peer A would attempt to reconnect to B because it learnt about A from other peers (rather than having been told in `weave connect`).

**Comment by elianka** [comment]
i know now all weave peers keep the same topology(connection information), so there is no use to cut one connection when there are other connections between two peers.
my achieve is very simple, just cut the connection to peerB on peerA, meanwhile peerB is still running and connect to other peers, such as peerE. it is impossible?
for example: peerA <-> peerB, peerA<->peerE, peerB<->peerC, peerB<->peerD. which <-> represent connection between two peers. now i want to cut the connection between A and B. 
weave forget prevents reconnection, but not to cut connection.

**Comment by rade** [comment]
> `weave forget` prevents reconnection

It does not. When you run `weave forget B` on A, then A could still find out about B from other peers and hence attempt to connect to it.

**Comment by rade** [comment]
The use case `weave connect` and `weave forget` are designed to handle is adding a peer to a weave network when the existing peers are behind a firewall.

It is not clear what use case you have in mind. Splitting a weave network?

**Comment by elianka** [comment]
thanks. got your point.
actually, i am just curious about these weave operations, and there is no concrete use case except the example previous which sounds like a splitting network.
