### ISSUE TITLE
Unsolicited arp on new connection doesn't always work

### ISSUE THREAD

**Issue by bboreham** [weaveworks/weave#2316]
Seen in #2313 - if we take the sleep out of the smoke-test then it usually fails the last ping.

`tcpdump` shows that the ping is using the MAC address of the previous container, and the arp table shows this entry as `REACHABLE` inside the pinging container (c1).  So somehow the unsolicited arp is not reaching c1 or is being ignored.

Various lengths of sleep down to about 0.3 seconds let it work, but 0.2 and below make it flaky.

**Comment by bboreham** [comment]
Further investigation shows that test 300 fails in a very similar way, if you take out the delays caused by `docker stop` (by replacing with `docker rm -f`).

**Comment by bboreham** [comment]
We note that Linux defaults the `locktime` during which arp updates are ignored to 1 second.  But inspection of the code at https://github.com/torvalds/linux/blob/master/net/ipv4/arp.c#L858 suggests that gratuitous arps override the `locktime`.

**Comment by rade** [comment]
In #2313 you wrote
> However the smoke-test does not work without the sleep between killing the old container and creating the new container. I haven't yet figured out why it is necessary.

Does the sleep definitely have to be in *that* place? In particular, placing it just before the "ping" doesn't work?

**Comment by brb** [comment]
Taking a look at https://github.com/torvalds/linux/blob/v4.2/net/ipv4/arp.c#L629 explains what happens on `c1`:

1. In the case of the second unsolicited ARP request (due to `c3`), `is_garp`(="is unsolicited ARP request") is set to `false`, because `/proc/sys/net/ipv4/conf/ethwe/arp_accept` is not set (it defaults to 0 (="ignore an unsolicited ARP request if an entry for a dst IP does not exist")) which prevents from executing the https://github.com/torvalds/linux/blob/v4.2/net/ipv4/arp.c#L804 branch.
2. Because of `is_garp=false` and the recently inserted entry (due to the `c2` unsolicited ARP request), `override` is set to `false` which prevents from updating the ARP cache on `c1`.

Also, the first unsolicited ARP request (originating from `c2`) is being ignored due to `arp_accept`.

**Comment by brb** [comment]
As mentioned in the comment above, `arp_accept` solves the problem, however at the same time it weakens a security.
