### ISSUE TITLE
Test 830 is flaky

### ISSUE THREAD

**Issue by bboreham** [weaveworks/weave#2329]
Failing in in gratuitous arp test - perhaps random timing?

https://circleci.com/gh/weaveworks/weave/6003
https://circleci.com/gh/weaveworks/weave/6012
https://circleci.com/gh/weaveworks/weave/6038

Possibly related to #2316?

**Comment by rade** [comment]
We are seeing this quite a lot.

**Comment by brb** [comment]
Setting the sleep time in the test case to 2 seconds should eliminate the failures, because  `LOCKTIME` (https://github.com/torvalds/linux/blob/v4.2/net/ipv4/arp.c#L176) which prevents from the ARP entry update is 1 sec + 1 sec for tolerating timer delays due to machines running on a non bare-metal.

**Comment by brb** [comment]
Pushed directly to the `1.6` branch.

**Comment by brb** [comment]
Reopening. Seems that 2 secs are not enough: https://circleci.com/gh/weaveworks/weave/6644

**Comment by awh** [comment]
Fixed by 7a81bc2ddc2f843fa230089800169fdb3050229f
