### ISSUE TITLE
'weave setup' on Docker-for-Mac 1.12.0-rc3 fails with cni mount error

### ISSUE THREAD

**Issue by pidster** [weaveworks/weave#2434]
`WEAVE_VERSION=latest weave setup` reports the following:

    pidster@ $ WEAVE_VERSION=latest weave setup
    docker: Error response from daemon: Mounts denied: 
    The paths /etc/cni and /opt/cni
    are not shared from OS X and do not belong to the system.
    You can configure shared paths from Docker -> Preferences...

I am on Docker For Mac 1.12.0-rc3-beta18 (build: 9996)

**Comment by pidster** [comment]
Versions 1.5.0, 1.6.0 also report the same error.

**Comment by pidster** [comment]
See also: https://github.com/weaveworks/scope/issues/1649

**Comment by errordeveloper** [comment]
Please see https://github.com/weaveworks/scope/pull/1650/commits/0ad6392a7890c2976fa45125c7ddb1849af0ee4a#diff-31a1fd140be4bef2d11e121ec9a18a58R127 for more details on this.

**Comment by bboreham** [comment]
Is it possible that Docker will try to mount those dirs from the Mac filesystem?  We don't want that.

**Comment by rade** [comment]
> Is it possible that Docker will try to mount those dirs from the Mac filesystem?

Not according to the commit @errordeveloper linked to above, which says "Docker for Mac (as of beta18) looks for this path on VM first, and when it doesn't find it there, it assumes the user refers to the path on Mac OS".

Also, if there was a problem with mounting /, we would have found out about it by now, since that is what `weave launch` does.
