### ISSUE TITLE
eliminate need for 'weave expose' when using CNI

### ISSUE THREAD

**Issue by rade** [weaveworks/weave#2485]
@bboreham says

> It occurs to me we could take out the need to call `weave expose` after the router is running, because we know enough to set up the masquerade rules before the router is running.

**Comment by bboreham** [comment]
The CNI plugin will now set up masquerade rules when it runs, but it will only run when required to do so by a pod - we still need something to set up the masquerade rules on each host. 

This issue is referring to the order in which operations are performed, and since we now do a bunch of things after starting the router process (e.g. reclaiming IP addresses) I'm going to close it: there is no benefit in moving just one step of many.
