### ISSUE TITLE
Cannot use uts.Release[:] (type []uint8) as type []int8

### ISSUE THREAD

**Issue by larmog** [weaveworks/weave#2506]
I'm trying to build weave `1.6.1` for `armhf` and get this compile error: 
<pre>
make: Entering directory '/go/src/github.com/weaveworks/weave'
go build -i -ldflags "-extldflags \"-static\" -X main.version=git-11f56031f150" -tags netgo -o prog/weaver/weaver ./prog/weaver
# github.com/weaveworks/weave/prog/weaver
prog/weaver/checkpoint.go:37: cannot use uts.Release[:] (type []uint8) as type []int8 in argument to charsToString
</pre>

See the attached build script how to reproduce.
[build.sh](https://github.com/weaveworks/weave/files/460342/build.sh.txt)

**Comment by 2opremio** [comment]
I don't have an arm machine around to reproduce with your script but it happens because [Utsname](https://golang.org/pkg/syscall/#Utsname) is architecture dependent.

The following quick patch should get you going for now (note that this will break x86 and we would need a more robust way if/when upstreaming it).

```patch
diff --git a/prog/weaver/checkpoint.go b/prog/weaver/checkpoint.go
index fac1b08..840af8d 100644
--- a/prog/weaver/checkpoint.go
+++ b/prog/weaver/checkpoint.go
@@ -50,7 +50,7 @@ func checkForUpdates(dockerVersion string, network string) {
 	checker = checkpoint.CheckInterval(&params, updateCheckPeriod, handleResponse)
 }
 
-func charsToString(ca []int8) string {
+func charsToString(ca []uint8) string {
 	s := make([]byte, len(ca))
 	i := 0
 	for ; i < len(ca); i++ {
```

As you have probably figured out by now, we don't officially support ARM but we thank you for looking into it and might consider upstreaming your changes once you get it to a working state.

**Comment by errordeveloper** [comment]
> ...we would need a more robust way if/when upstreaming it

I think you'd simply need to use build tags and have separate definitions of the func.

**Comment by rade** [comment]
why not simply inline the function? then no type signature is needed.
