### ISSUE TITLE
Can't ping between containers in the same subnet when using weave expose for a part of the subnet

### ISSUE THREAD

**Issue by erandu** [weaveworks/weave#2516]
I have created a docker network via :
`docker network create -d weave --subnet=192.168.0.0/16 --opt=works.weave.multicast weave1`
After that I launch some containers in this network without assigning them an IP. So they took IPs like 192.168.0.2, 192.168.0.3 , etc...
Then I run `./weave expose 192.168.1.1/24`. And if I start a container by assigning to this one  IP 192.168.1.2,
(docker run --ip 192.168.1.2 --net=weave1) this container is not able to talk to other containers. After, if I do `./weave hide 192.168.1.1/24`, this container is able to talk with other containers.
Output of weave ps :
```
~ $ ./weave ps
weave:expose 06:e8:16:3b:6f:2b 192.168.1.1/24
48e7c6dc3adc a6:9b:9f:9e:9e:0f 192.168.1.2/16
99971cf74f81 72:48:89:38:b5:e3 192.168.0.3/16
b424809cda62 7a:8b:3a:f6:2c:a3 192.168.0.2/16
```

192.168.0.3 and 192.168.0.2 are able to talk. But 192.168.1.2 and 192.168.0.3 are not able to talk for example.

**Comment by brb** [comment]
The problem is that exposing the smaller subnet (`192.168.1.1/24`) installs a route `192.168.1.0/24 dev weave  proto kernel  scope link  src 192.168.1.1` on the host. As you can see, this route does not cover e.g. `192.168.0.2`, thus this IP addr is treated as non-local and any traffic designated to the IP is sent over a default gateway.

To workaround, first of all, you need to create multiple networks with different subnets (keep in mind that multicast can be enabled only in one network, please see [the note at the bottom of the page](https://www.weave.works/docs/net/latest/plugin/plugin-how-it-works/)). Next, connect containers to all of them by `docker network connect $NETWORK $CONTAINER`. Finally, expose a subnet(s).

Alternatively, you could use [weave proxy](https://www.weave.works/docs/net/latest/weave-docker-api/) to achieve the desired behavior:

```
$ docker $(weave config) run --name c1 -e WEAVE_CIDR="net:192.168.0.0/24 net:192.168.1.0/24" -td alpine /bin/sh
$ docker $(weave config) run --name c2 -e WEAVE_CIDR="net:192.168.0.0/24 net:192.168.1.0/24" -td alpine /bin/sh
$ weave expose net:192.168.1.0/24
```
