### ISSUE TITLE
"ulogd_output_PCAP.so: No such file or directory" on latest `weaveworks/weave-npc` images

### ISSUE THREAD

**Issue by webwurst** [weaveworks/weave#2732]
This file seems to be not part of the current `alpine` image, here the full error message:
```
/ # /usr/bin/weave-npc 
INFO: 2017/01/14 12:59:53.584401 Starting Weaveworks NPC git-81add752583a
INFO: 2017/01/14 12:59:53.586169 Serving /metrics on :6781
Sat Jan 14 12:59:53 2017 <7> ulogd.c:622 load_plugin: '/usr/lib/ulogd/ulogd_output_PCAP.so': Error loading shared library /usr/lib/ulogd/ulogd_output_PCAP.so: No such file or directory
Sat Jan 14 12:59:53 2017 <5> ulogd.c:843 building new pluginstance stack: 'log1:NFLOG,base1:BASE,pcap1:PCAP'
Sat Jan 14 12:59:53 2017 <7> ulogd.c:870 can't find requested plugin PCAP
Sat Jan 14 12:59:53 2017 <8> ulogd.c:1430 not even a single working plugin stack
Fatal error.
FATA: 2017/01/14 12:59:53.599400 ulogd terminated: exit status 1
```

It works for me if I am using `alpine:edge` as base image.

**Comment by awh** [comment]
Many thanks for the report @webwurst! Looks like alpine stripped the PCAP plugin from ulogd in the 3.4 -> 3.5 transition. We'll pin the weave-npc container to 3.4 and look in to why it was removed upstream...

**Comment by nhlfr** [comment]
This error still exists, images are not pinned to 3.4. The default ALPINE_BASEIMAGE value is `alpine` for non-arm builds:

https://github.com/weaveworks/weave/blob/master/Makefile#L28

That's why the latest image from dockerhub is failing with the error about ulogd. For now the only way for pulling the image which is working is to use git-84013c4452d1 tag.

Could you please re-open the issue?
