### ISSUE TITLE
Migrating between  --non-masquerade-cidr ranges in kubernetes

### ISSUE THREAD

**Issue by chrislovecnm** [weaveworks/weave#2874]
How does one migrate a cluster between different `--non-masquerade-cidr ` ranges with weave?  With the current configuration of kops we did not quite set the cidr range correctly, and would like to start using the correct range.  But how do we migrate clusters correctly to the new range?

**Comment by bboreham** [comment]
Trying to understand the context here: is it related to https://github.com/kubernetes/kops/pull/2091 ?

I see `--non-masquerade-cidr` as a flag to kubelet, but I can't see the value being used by the CNI code path.  In other words it should have no effect in a Weave Net install.

If the question relates to Weave Net's `--ip-alloc-range` flag, changing that will effectively create a new network: all the peers in the old network will refuse to talk to peers in the new network, until they all restart with the new setting.  In the newly-forming network, nothing will happen at all until a quorum of all the peers can vote to get started.  (For example, if you had 11 nodes, all the updated ones will stall until at least 6 have updated)

Since Weave Net defaults the IP subnet to the same value as `--ip-alloc-range`, pods with IP addresses on the old network will not necessarily be able to talk to pods on the new network. So I would also shut down as much as possible when making the change, and reboot all nodes afterwards.  It should be ok to do a rolling reboot.

**Comment by chrislovecnm** [comment]
1. `kubeAPIServer.serviceClusterIPRange: 100.64.0.0/13` should not overlap with the CIDR for weave
1. `kubeControllerManager.clusterCIDR` should not be set if you are using weave - it is not being used
1. ` kubelet.nonMasqueradeCIDR: 100.64.0.0/10` - we should not be setting this with weave
1. does kubelet need the clusterDNS?

*Implementation Notes*

1. Select different ip ranges for service ip addresses
1. We need to figure out routing between services
1. add a static route between nodes would help with service routing
1. We need figure out HA method for spanning routes between different service ip range, maybe BGP

**Comment by brb** [comment]
@chrislovecnm are there any unresolved questions?

**Comment by chrislovecnm** [comment]
We are testing this currently no questions
