### ISSUE TITLE
Releases v2.1.0 and v2.1.1 brake with WEAVE_DOCKER_ARGS defined

### ISSUE THREAD

**Issue by berlic** [weaveworks/weave#3182]
## What you expected to happen?

Expect `weave launch` to start weave.

## What happened?

Weave does not start.

## How to reproduce it?

```
# wget https://github.com/weaveworks/weave/releases/download/v2.1.1/weave
# chmod +x weave
# ./weave setup
# ./weave version
weave script 2.1.1
weave 2.1.1
# ./weave launch
582be657df402e11f2180c5f37bb1e538d675508fb4e374a8e91dc7922dbb816
# ./weave stop
# WEAVE_DOCKER_ARGS=--log-driver=json-file ./weave launch
unable to create container: API error (500): invalid reference format

```

## Anything else we need to know?

The problem seems to be introduced with PR #3110 that implements #2957.

Although issue description clearly says:

> ... although we have suggested that users set `WEAVE_DOCKER_ARGS` to add arbitrary more [arguments to docker run] ... 

the implementation lacks its support.

`weaveutil` [expects](https://github.com/weaveworks/weave/blob/v2.1.1/prog/weaveutil/container.go#L148) image name just after list of **supported** arguments:

```
cmdUsage("run-container", `[options] <image> <cmd> [[<cmd-options>] <cmd-arg1> [<cmd-arg2> ...]]
```

but `weave` script [injects](https://github.com/weaveworks/weave/blob/v2.1.1/weave#L1252) `WEAVE_DOCKER_ARGS` just before image name.

This results in `"Image": "--log-driver=json-file"` being passed to docker API.

**Comment by bboreham** [comment]
So this is an unannounced change to an undocumented feature.  Apologies for the inconvenience.

I don't think this is about the ordering of arguments - `weaveutil run` simply doesn't support what you tried, in any order.

If `--log-driver` support is something you particularly want you should file an issue requesting that, since we're never going to add all the `docker` flags in `weaveutil run`.  The end-game is to move all the logic from shell to Go at which point we won't need `weaveutil`.
