### ISSUE TITLE
Replace weave-local-pods ipset with physdev iptables rule

### ISSUE THREAD

**Issue by brb** [weaveworks/weave#3344]
We can get rid of the `weave-local-pods` ipset used by the weave-npc ingress rule `-A WEAVE-NPC -m set ! --match-set weave-local-pods dst -j ACCEPT` with `-A WEAVE-NPC -m physdev --physdev-out=vethwe-bridge -j ACCEPT`.

The former rule is insecure, as it might allow ingress traffic if the ipset is not properly maintained (e.g. due to crashing weave-npc as in https://github.com/weaveworks/weave/issues/3032#issuecomment-403397070) or if weave-npc lags behind processing updates from kube-apiserver.

**Comment by murali-reddy** [comment]
@brb We can use `physdev` module  when `Bridge` and `BridgedFastdp` are in use. But these rules can not work in case of `Fastdp` as there is no bridge. It seems like we can not use `physdev` asa solution that can work across all the modes. Let me know your thoughts.

**Comment by bboreham** [comment]
I think I would phrase that in a different way - the only reason we added the bridge to fastdp was because conntrack didn't work with our datapath "bridge-lite". So what you discovered would lead to the conclusion "Weave-npc only works with `BridgedFastdp`", which is not a big deal. Most people aren't using any network policies.

**Comment by bboreham** [comment]
After reviewing the PR, I realise I over-stated "Weave-npc only works with BridgedFastdp". Should be more like "if you use weave-npc and Weave Net, you can't use a non-bridged mode".

I still like the idea that weave-npc is not tied to Weave Net; for instance it could work with kubenet with a little tweaking to the rules. (although I haven't tried - maybe that's incorrect)

**Comment by murali-reddy** [comment]
Its valid point to keep Weave-npc independently usable with any other CNI/kubenet etc. If we need to keep that goal then should we even fix this issue (or at least with the use of physdev)? As use of ipset is generic solution that work with any CNI that uses bridge or CNI's that use L3. Also we don't have to worry about mode of weave net.

as far as the rationale of this issue

> The former rule is insecure, as it might allow ingress traffic if the ipset is not properly maintained (e.g. due to crashing weave-npc as in #3032 (comment)) or if weave-npc lags behind processing updates from kube-apiserver.

Is it not reasonable to assume things will only be eventually consistent. There will always be case (due to `weave-npc lags behind processing updates from kube-apiserver`) where it is insecure when actual state is not desired state?

**Comment by bboreham** [comment]
Yes, I still think it is worth fixing.  It's more efficient too, I think, to lose the ipset.
