### ISSUE TITLE
[dns] return all matching local records

### ISSUE THREAD

**Issue by rade** [weaveworks/weave#338]
ATM, weavedns only returns the first matching record for a local name / reverse lookup. But there can be multiple matching records; all of them should be returned.

**Comment by rade** [comment]
This should apply to both direct queries and queries received over mDNS.

@squaremo @bboreham any gotchas here? I suppose it could be deemed somewhat inconsistent/strange/surprising to respond with all matching records from one peer, but not across all peers.

**Comment by squaremo** [comment]
> any gotchas here?

Nope, don't think so. There is still the problem of having a consistent way of answering a query for which there are multiple answers on the network, which this may or may not help; *just* doing this will muddy the waters a bit, since instead of getting one answer from some host or no answer, a question will get some answers *all from the same host* or no answer.

**Comment by inercia** [comment]
@rade Current WeaveDNS can return all the answers with "--max-answers=0", so is this issue still valid?  If so, what is missing?

**Comment by rade** [comment]
Users shouldn't have to supply special configuration parameters for something that should just work.

I suspect this issue will get resolved as part of #733.

**Comment by rade** [comment]
> I suspect this issue will get resolved as part of #733.

Pretty sure that is the case, in the light of #826.
