### ISSUE TITLE
[dns] failure during launch-dns can lead to long pause

### ISSUE THREAD

**Issue by bboreham** [weaveworks/weave#393]
If the `weavedns` container fails during start-up, but after the script gets into `populate_dns`, then it will take about 5 seconds to bail out because it doesn't check to see if the container is still running; it just repeatedly calls `curl` then `sleep`.

Also it doesn't check to see if a valid IP was returned from 'docker inspect'.

**Comment by rade** [comment]
Looks like things have moved on since this was filed...

1. We now wait for the dns container to respond to a status request, before doing anything else. This will catch any issues during dns container startup.
2. Following that, we just invoke 'curl' for each container IP. That invocation has a configured connect timeout of 3 seconds. If it fails the weave script exits with an error code. There is no message though; I shall fix that.
