### ISSUE TITLE
[ipam] automatic allocation of addresses for `weave expose`

### ISSUE THREAD

**Issue by stlalpha** [weaveworks/weave#485]
If I instantiate an allocator for 172.16.100.0/24 on the weave network, I want the hosting operating system (the one that is hosting the weave router docker image) to be able to request and receive a dynamic IP from that allocator.  It should be able to fully participate in the ip allocation/deallocation feature set as the containers themselves can.  Ideally this is something akin to the current capability of:

weave expose 172.16.100.20/24

But instead - you would be able to do something like:

weave attach 172.16.100.0/24 

from the hosting operating system.

**Comment by rade** [comment]
This is already on our roadmap, though hadn't hitherto been captured as a separate issue. So thank you.

The general approach we have been taking with IPAM is to tweak the existing command sets such that where they currently accept a CIDR, they will (also) except a) nothing, b) b a network. So we'd likely tweak `weave expose` rather than introduce a separate command.

**Comment by rade** [comment]
I believe this will be addressed by #563.

**Comment by dpw** [comment]
With #563, we automatically allocate an address when you do `weave expose`.
