### ISSUE TITLE
Published documentation tracks master instead of latest released version

### ISSUE THREAD

**Issue by awh** [weaveworks/weave#520]
The documentation linked from the github repo (including the 'official' documentation page at http://zettio.github.io/weave/) is based on current master, not the latest release build (which is what the readme asks people to install). Consequently the documentation does not match what users are running, causing confusion: http://stackoverflow.com/questions/29401418/docker-weave-and-weavedns-issues

**Comment by rade** [comment]
We can tackle this in phases...

1. make the published docs always represent the latest released version. This requires some additional branching magic and script tweaking so that a) when we merge new features we have some place to merge the docs that doesn't end up updating the web site, and b) we have a way to update the published docs, to fix typos etc.

2. separately publish the 'next' version of docs, i.e. covering all the changes on master.

3. keep published snapshots of the docs for all published releases.

There is some extra difficulty here in that the main README forms quite an important part of the documentation.

**Comment by rade** [comment]
This issue has been mostly addressed by #604.

The docs published on the [*weaveworks* website](http://docs.weave.works/weave/latest_release/index.html) now refer to the latest released version. This does take care of (1), except we currently have no documented way of updating the published docs (and merge such changes into master) in order to fix typos, etc. And the docs on github still refer to the master version. #612 should fix that.

#604 also takes care of (2) and (3) by publishing docs to http://docs.weave.works/weave/master, http://docs.weave.works/weave/v0.10.0, etc.

**Comment by rade** [comment]
Surely this is fixed now. Closing. @errordeveloper if that is wrong then please re-open.
