### ISSUE TITLE
Error message when you don't have permission to run could stand improvement

### ISSUE THREAD

**Issue by bboreham** [weaveworks/weave#524]
````
$ weave status
2015/04/08 14:39:32 Post http:///var/run/docker.sock/v1.15/containers/create: dial unix /var/run/docker.sock: permission denied
````

It used to say something like 'weave must be run as root'.  (I believe this message is actually coming from Docker)

**Comment by rade** [comment]
I'm guessing this bug was introduced via #388.

**Comment by rade** [comment]
Hmm. So previously the main motivation for requiring root (and hence checking for that) was all the crazy configuration we had to do perform on the host. But that is no longer happening unless `--local` is supplied (in which case we do still perform the root check).

AFAIK there is actually no intrinsic requirement to run as 'root' in order for the docker client to talk to the daemon, eg. when talking to the daemon over a tcp socket instead of unix domain socket. So, for example, when I launch my docker daemon with `-H tcp://127.0.0.1:4243 -H unix://`, and then in my env set `DOCKER_HOST=localhost:4243` then I can run `weave launch` successfully without being root.

So it's difficult to construct a reliable test for when running as root is required.

Perhaps we should just leave things as they are? After all, anybody working with docker should be familiar with encountering that error.

@squaremo thoughts?

**Comment by squaremo** [comment]
Yes I had difficulty deciding what was TRTTD there. I don't think we should assume that the docker client needs to be run as root -- or rather, we should trust that the user knows when they will need to run as root.
