### ISSUE TITLE
Weave local cache?

### ISSUE THREAD

**Issue by lvangool** [weaveworks/weave#593]
In my scenario, a host with X containers is removed from the cluster. Subsequently, I may allocate one of that old host's weave IPs to a new container on another machine in the cluster. We're seeing that in that scenario we sometimes get routing errors. Rebooting hosts fixes everything, as does simply incrementing the IP addresses indefinitely. However to make it more scalable we need to re-use IPs that are no longer associated with the cluster. 

Does weave have a local cache of routing endpoints? If so:
1) what is it's expiry profile
2) is there a way to manually flush it?
3) is there a way to query all IPs currently in the cache?

**Comment by rade** [comment]
From the [0.10.0](https://github.com/weaveworks/weave/releases/tag/v0.10.0) release notes...
"avoid excessive ARP caching. This prevented connectivity to containers which were restarted with the same IP or otherwise given an IP that was recently in use. Connectivity to weave exposeed addresses was similarly affected. #439/#441/#457"

Are you perhaps running into that?

**Comment by lvangool** [comment]
Yes - quite possibly - I'll upgrade to 0.10.0 and get back if that doesn't resolve this issue.
Thanks again.

**Comment by rade** [comment]
@lvangool have you had chance to give 0.10 a try?

**Comment by lvangool** [comment]
@rade yes, I've upgraded and haven't seen this problem occurring as yet. Admittedly I haven't done mass testing though; will reopen this again if I see it again.
