### ISSUE TITLE
Introduce debug option to `weave` script

### ISSUE THREAD

**Issue by awh** [weaveworks/weave#618]
Now that the bulk of the weave script executes inside the weaveexec container, it's more difficult to access information about its execution for debugging purposes. Add a debug option to the script that:

* Starts weaveexec container without `--rm` option so logs can be inspected
* Enables shell debug via `set -x`

**Comment by rade** [comment]
Perhaps have a WEAVE_DEBUG env var, which also gets passed to the "inner" script. That way if we feel the need to modify that script's behaviour for debugging, we can.

**Comment by rade** [comment]
re "shell debug"... this is for the "inner" script; we don't need anything special for the outer script, since that is easily traced with `sh -x ./weave ...` already.

**Comment by rade** [comment]
This turned out to be much simpler than I expected. I'm setting `-x` in the script when `WEAVE_DEBUG` is present, and pass the env var along in the `weavexec` invocation, so the embedded script in turn does the same. This results in both the outer and inner script's output appearing in stderr.

I decided to include the outer script execution since we will generally want to see both the outer and inner, and it is easier to ask users to do one thing instead of two.

There is no need to drop the --rm since all the debug output goes to stderr.
