### ISSUE TITLE
[ipam] don't leak or double-allocate IPs, on normal restart

### ISSUE THREAD

**Issue by rade** [weaveworks/weave#678]
ATM, when a peer restarts, one of the following scenarios occurs:

1. The peer got gracefully removed from the weave network on shutdown (e.g. `weave reset`), and starts with a new identity. Everybody is happy. No IPs leaked or double-allocated.
2. The peer didn't get removed gracefully, and lost its identity. The ranges it used to own are leaked and must be recovered with `rmpeer`.
3. The peer retained its identity on restart, gets told by other peers (via gossip) what IP ranges it used to owned, and happily lives ever after.
4. The peer retained its identity on restart, but the information it is told via gossip about the IP ranges it owns is out of date, e.g. if it had given away part of its range to some other peer just before dying and that information hasn't propagated through the entire network yet (either because of delays or partitions). As a result the peer may allocate duplicate IPs and/or eventually explode because it gets told more up-to-date, but conflicting, range ownership info.

We really want to eliminate (4). Persisting the ring is one way to accomplish that. This also helps with (2) since it would allow us to retain a peer's identity across most restarts, thus converting such restarts into case (3) or (4).

**Comment by dpw** [comment]
We may want to widen this issue to "persist gossiped IPAM state" (not just the ring state), or create another issue for that and link to it, because it helps in other scenarios.  Two more examples:

* After the ring is seeded, a minority of nodes are partitioned off and restarted.  Currently, they will stall in paxos due to not having a quorum.  Persistence would allow them to regain their ring state and so proceed with allocations.

* Imagine that a freshly stated cluster is partitioned into two so that one partition is a quorum and the other is lacking a quorum by a single node.  The partition with a quorum reaches paxus consensus and seeds the ring, the other partition cannot.  But then a node restarts and jumps the partition simultaneously.  The former minority partition can now reach a conflicting consensus.  If persistence allowed that node to bring is old state with it, this would not happen.

**Comment by rade** [comment]
> We may want to widen this issue to "persist gossiped IPAM state"

Good point. I was trying to phrase the issue in terms of the problem rather than the solution. So perhaps open a separate issue and then we can have one PR which addresses both?

**Comment by rade** [comment]
Following #1866, (2) is now much rarer.

**Comment by bboreham** [comment]
Fixed by a combination of #1967 and #1973
