### ISSUE TITLE
make Java InetAddress.getLocalHost() (similar to hostname -i) return the weave IP address

### ISSUE THREAD

**Issue by bboreham** [weaveworks/weave#68]
At present, a container started in the way described in the weave README will have two IP addresses: one assigned by Docker and one assigned through weave.  So `hostname -I` will return something like:

    root@9b903541c5a7:/# hostname -I
    172.17.0.72 10.0.0.61 

however, `hostname -i` returns the Docker-assigned IP:

    root@9b903541c5a7:/# hostname -i
    172.17.0.72

I would prefer `hostname -i` to return the weave address

**Comment by rade** [comment]
As of docker 1.4.1 you can add entries to /etc/hosts with `--add-host=name:IP`. Alas those entries get appended, which is of no use to resolving this issue.

**Comment by qxo** [comment]
weave run with --add-host=name:IP --net=none will solve the problem!
weave should add these argument as default :)
eg:
```shell
ip=10.2.1.26;weave run  --with-dns $ip/24 --net=none --add-host=a1:$ip -ti -h a1  ubuntu

**Comment by rade** [comment]
`--net=none` disables docker networking, i.e. you are left with *just* weave networking. That may be fine for some users, but it's not something we'd want to have as the default behaviour.

**Comment by rade** [comment]
Also, if you are running with `--net=none` then the problem described in this issue doesn't manifest in the first place.

**Comment by rade** [comment]
`/etc/hosts` [*is* writable](http://stackoverflow.com/questions/19414543/how-can-i-make-etc-hosts-writable-by-root-in-a-docker-container/25613983#25613983):

````
$ weave launch && weave launch-dns && weave launch-proxy
47921135b7b4943de2a1f56ff44a2060206e4ee8c7fc136a8e237958b710529a
4f19482849dc1e3166506b7da1aef5f9aebe6615f6c944eb1fae72dedf3bc496
4bc93553a81228a9253e58e48d21aebc582e4587b10ddded1e865b0ff2a94df6
$ eval $(weave proxy-env)
$ docker run --name=foo -ti ubuntu
root@foo:/# hostname -i
172.17.0.63
root@foo:/# echo > /etc/hosts
root@foo:/# hostname -i
10.128.0.2
````

I also tried prepending an entry and using docker links at the same time, to see whether docker's /etc/hosts updating stomps on the file. It doesn't; it just updated the entry for the link and left my modifications alone. The only gotcha I can see is that because the file is mounted, there is no atomic way to update it.

So, anyway, strawman proposal: make `weave run/attach` (and thereby also the proxy) prepend an entry to /etc/hosts with the weave IP.

We should probably also deal with dynamic add/remove via `weave attach/detach`.

**Comment by rade** [comment]
> make `weave run/attach` (and thereby also the proxy) prepend an entry to /etc/hosts with the weave IP.

The trouble is that we have no easy way to do that from the script since we somehow need to reach into the container's filesystem. `docker exec` is no good here since it can only execute commands that are present inside the container. The proxy could do it easily, in weavewait (since that is running inside the container). That doesn't help with dynamic attach/detach, but perhaps is still a worthwhile improvement, despite the inconsistency it creates with `weave run`.

**Comment by errordeveloper** [comment]
Running Mesos in Docker with Weave & DNS is also problematic due to this, as it looks up it's hostname and registers own cluster membership with the IP address it finds, which turns out to be Docker IP, of course...
