### ISSUE TITLE
`weave status` should only succeed if weave is running

### ISSUE THREAD

**Issue by MaximeHeckel** [weaveworks/weave#784]
I recently encountered a strange issue when executing the command `weave --local status` in a script where I set `set -e` at the beginning.
The weave container was stopped at that moment and this command printed the following message  ...

```
weave container is not present; have you launched it?

```

... and the script kept going without exiting ! 

I think it might be due to a wrong exit code.

As a workaround, I needed to do that
`/weave --local status | grep -qv "weave container is not present; have you launched it?"`

**Comment by rade** [comment]
what version of the script were you running?

**Comment by MaximeHeckel** [comment]
v 0.10.0

**Comment by rade** [comment]
The script deliberately returns 0.

Perhaps that is not all that useful.

The issue is that it's not clear what should happen when weave isn't running but weavedns is, or vice versa.

weavedns is optional, so returning a non-zero status when that isn't there seems wrong.

And you may still want to see the weavedns status even when weave isn't running.

So I guess we could make the script return a non-zero status when weave isn't running, but still show the weavedns status (and always ignore any errors from that).
