### ISSUE TITLE
[dns] failure in TestZoneRefresh

### ISSUE THREAD

**Issue by rade** [weaveworks/weave#798]
Have seen this once while running `go test -tags netgo ./nameserver/` in #792.

````
INFO: 2015/05/29 14:07:16.794274 TestZoneRefresh starting
INFO: 2015/05/29 14:07:16.794400 [zonedb] Using mDNS on all interfaces
INFO: 2015/05/29 14:07:16.794405 [zonedb] Starting 4 background name updaters
INFO: 2015/05/29 14:07:16.794409 [zonedb] Using mDNS on all interfaces
INFO: 2015/05/29 14:07:16.794411 [zonedb] Starting 4 background name updaters
--- FAIL: TestZoneRefresh (0.10s)
	zone_lookup_test.go:55: Db #1 after the lookup:
		weave:remote: , 
		someident: mysql.weave.local.[10.2.8.4]
	zone_lookup_test.go:81: Db #1 after the second lookup:
		someident: mysql.weave.local.[10.2.8.4]
		weave:remote: mysql.weave.local.[10.2.8.5]/TTL:30, mysql.weave.local.[10.2.8.6]/TTL:30
	util.go:134: Expected lookup result length 4 but got 1
		goroutine 280 [running]:
		github.com/weaveworks/weave/testing.stackTrace(0xc2081d5800, 0x0, 0x0)
			/home/matthias/go/src/github.com/weaveworks/weave/testing/util.go:143 +0x88
		github.com/weaveworks/weave/testing.StackTrace(0x0, 0x0)
			/home/matthias/go/src/github.com/weaveworks/weave/testing/util.go:138 +0x35
		github.com/weaveworks/weave/testing.Fatalf(0xc208134ab0, 0x8748b0, 0x19, 0xc2081d3d20, 0x3, 0x3)
			/home/matthias/go/src/github.com/weaveworks/weave/testing/util.go:134 +0x27
		github.com/weaveworks/weave/testing.AssertEqualInt(0xc208134ab0, 0x1, 0x4, 0x869d30, 0x14)
			/home/matthias/go/src/github.com/weaveworks/weave/testing/util.go:51 +0x1b3
		github.com/weaveworks/weave/nameserver.TestZoneRefresh(0xc208134ab0)
			/home/matthias/go/src/github.com/weaveworks/weave/nameserver/zone_lookup_test.go:108 +0x1cb8
		testing.tRunner(0xc208134ab0, 0xa0ecb0)
			/usr/local/go/src/testing/testing.go:447 +0xbf
		created by testing.RunTests
			/usr/local/go/src/testing/testing.go:555 +0xa8b
INFO: 2015/05/29 14:07:16.896150 [zonedb] Using mDNS on all interfaces
WARNING: 2015/05/29 14:07:16.896396 [zonedb] Remote info will not be garbage collected
INFO: 2015/05/29 14:07:16.896665 [zonedb] Removing everything for ident 'deadbeef'
INFO: 2015/05/29 14:07:16.896684 [zonedb] Removing everything for ident 'cowjuice'
INFO: 2015/05/29 14:07:16.897116 [zonedb] Using mDNS on all interfaces
WARNING: 2015/05/29 14:07:16.897266 [zonedb] Remote info will not be garbage collected
INFO: 2015/05/29 14:07:16.897294 [zonedb] Removing everything for ident 'foobar'
FAIL
````

I am tentatively putting this into 0.11.1. If it turns out that the issue is with post-0.11 code, or just with the test code, then we should move it to 'next'.

**Comment by awh** [comment]
I just had this on a travis build of my #706 PR, even though the tests passed locally. I passed when I ran it again, so there's some race condition here...

**Comment by inercia** [comment]
After running the test many times, it shows in some cases:
```
while /bin/true ; do go test -tags netgo ./nameserver/ -test.run=TestZoneRefresh -race -v &>> tests.log ; done
$ grep "^\-\-\-\ FAIL" tests.log  | wc -l
2
$ grep "^\-\-\-\ PASS" tests.log  | wc -l
2321
```

The problem seems to happen when moving the clock forward in the test: it does not run all the things it should. We would expect:

```
DEBUG: 2015/05/30 11:38:40.982142 >>>>>>> Moving clock forward 1 seconds - Time traveling >>>>>>>
DEBUG: 2015/05/30 11:38:40.982181 [zonedb] Refreshing name 'mysql.weave.local.' with mDNS...
DEBUG: 2015/05/30 11:38:40.982213 [zonedb] Looking for name 'mysql.weave.local.' in local database
DEBUG: 2015/05/30 11:38:40.982289 [zonedb] Obtained 3 IPs for name 'mysql.weave.local.' with mDNS: 3 added, 0 removed
DEBUG: 2015/05/30 11:38:40.982330 [zonedb] Rescheduling update for 'mysql.weave.local.' in 5.00 secs
DEBUG: 2015/05/30 11:38:40.982388 [zonedb] Periodic updater: new request for mysql.weave.local.: sleeping for 5.00 secs...
DEBUG: 2015/05/30 11:38:40.982430 <<<<<<< Time travel finished! We are at 1970-01-01 01:00:48 +0100 CET <<<<<<<
```
while I get:

```
DEBUG: 2015/05/30 12:18:31.405061 >>>>>>> Moving clock forward 1 seconds - Time traveling >>>>>>>
DEBUG: 2015/05/30 12:18:31.405114 <<<<<<< Time travel finished! We are at 1970-01-01 01:00:48 +0100 CET <<<<<<<
```

I'm pretty sure this is a failure that only affects unit tests, but still I'm trying to figure out why...

**Comment by inercia** [comment]
So this is my guess:

We schedule updates by sending a request to an actor. All names updates have the same frequency, so this actor consumes the request, [sleeps until the time comes](https://github.com/weaveworks/weave/blob/master/nameserver/zone_lookup.go#L326), and then [forwards the request to an updater](https://github.com/weaveworks/weave/blob/master/nameserver/zone_lookup.go#L340). Then an updater will [perform the mDNS lookup](https://github.com/weaveworks/weave/blob/master/nameserver/zone_lookup.go#L284) and [send the request back to the actor](https://github.com/weaveworks/weave/blob/master/nameserver/zone_lookup.go#L295). 

The problem comes from the fact that the mocked clock can forward the clock by keeping record of  pending timers: when me move the clock forward, it [loops through the timers](https://github.com/benbjohnson/clock/blob/master/clock.go#L76), [executing them](https://github.com/benbjohnson/clock/blob/master/clock.go#L136) until no more timers are pending.

So, in this case, the mocked clock will continue with the time travel as long as we create timers while moving the clock forward. But, if the mocked clock loop takes control and no timer has been scheduled (eg, a request is in the channel and it has not been consumed yet), the time travel will be interrupted.

So a hackish solution that seems to reduce the frequency of the error is to insert multiple `runtime.Gosched()` after [the timer is executed](https://github.com/benbjohnson/clock/blob/master/clock.go#L137) (in fact, the library [does something similar](https://github.com/benbjohnson/clock/blob/master/clock.go#L107)), but I'm still trying to confirm this theory, and maybe to find a more general solution...

**Comment by rade** [comment]
At the expense of generality, if you know what actor/channels are involved in the tests, you could 'flush' them, e.g. by invoking a 'synchronous' method.

**Comment by rade** [comment]
or you could configure the channel size to 0.

**Comment by inercia** [comment]
@rade With channel size, the program blocks. From [Go's spec](https://golang.org/ref/spec), _"If the capacity is zero or absent, the channel is unbuffered and communication succeeds only when both a sender and receiver are ready"_

**Comment by rade** [comment]
I am well aware of the go channel semantics. It's interesting that a channel size of 0 breaks things in weavedns. Ideally that wouldn't be the case, but that's a separate issue from this one.

**Comment by inercia** [comment]
This blocks when channel sizes are 0 because I changed some things for running synchronously. Restoring their previous asynchronous behaviour only fixes the blocking, not the test failure...

**Comment by awh** [comment]
Got another failure in this test with different symptoms - is it the same cause?

https://travis-ci.org/weaveworks/weave/builds/66364210
````
INFO: 2015/06/11 11:21:00.722419 TestZoneRefresh starting

INFO: 2015/06/11 11:21:00.722512 [zonedb] Using mDNS on all interfaces

INFO: 2015/06/11 11:21:00.722523 [zonedb] Starting 4 background name updaters

INFO: 2015/06/11 11:21:00.722531 [zonedb] Using mDNS on all interfaces

INFO: 2015/06/11 11:21:00.722536 [zonedb] Starting 4 background name updaters

--- FAIL: TestZoneRefresh-2 (0.10s)

	zone_lookup_test.go:55: Db #1 after the lookup:

		weave:remote: 

		someident: mysql.weave.local.[10.2.8.4]

	zone_lookup_test.go:81: Db #1 after the second lookup:

		someident: mysql.weave.local.[10.2.8.4]

		weave:remote: mysql.weave.local.[10.2.8.6]/TTL:30, mysql.weave.local.[10.2.8.5]/TTL:30

	util.go:134: Unexpected remote name info

		goroutine 321 [running]:

		github.com/weaveworks/weave/testing.stackTrace(0xc208129d00, 0x0, 0x0)

			/home/travis/gopath/src/github.com/weaveworks/weave/testing/util.go:143 +0x88

		github.com/weaveworks/weave/testing.StackTrace(0x0, 0x0)

			/home/travis/gopath/src/github.com/weaveworks/weave/testing/util.go:138 +0x35

		github.com/weaveworks/weave/testing.Fatalf(0xc2080e23f0, 0x8465d0, 0xd, 0xc20836dd18, 0x1, 0x1)

			/home/travis/gopath/src/github.com/weaveworks/weave/testing/util.go:134 +0x27

		github.com/weaveworks/weave/testing.AssertFalse(0xc2080e23f0, 0x876501, 0x879450, 0x10)

			/home/travis/gopath/src/github.com/weaveworks/weave/testing/util.go:18 +0x10a

		github.com/weaveworks/weave/nameserver.TestZoneRefresh(0xc2080e23f0)

			/home/travis/gopath/src/github.com/weaveworks/weave/nameserver/zone_lookup_test.go:92 +0x167e

		testing.tRunner(0xc2080e23f0, 0xa21dc0)

			/usr/local/go/src/testing/testing.go:447 +0xbf

		created by testing.RunTests

			/usr/local/go/src/testing/testing.go:555 +0xa8b
````
