### ISSUE TITLE
Remove `weave launch-dns` and `weave stop-dns`

### ISSUE THREAD

**Issue by awh** [weaveworks/weave#840]
* Remove `weave launch-dns` and `weave stop-dns`
* Add `--dns <cidr>` option to `weave launch` that starts weaveDNS if specified

Requires changes to script, tests, docs.

**Comment by rade** [comment]
One challenge here is what to do with all the DNS options; the script needs to somehow recognise them so it can pass them to weavedns and not weaver.

Suggestion: prefix all DNS options with `dns-`. The prefix would be stripped by the script, so weavedns would see its current, non-prefixed options.

And perhaps the CIDR should be supplied with `dns-net <cidr>`.

Another thing to figure out is error handling...

- What should happen when one (but not the other) of weave or weavedns is already running? This normally shouldn't happen, in this new scheme, since both should be started and stopped together. But of course one of them may have died, or the user started one of them in some exotic way. I reckon we should *not* start the other, report "already running" and exit with an error. Other options: a) start the other but still exit with an error (weird), b) start the other but don't exit with an error (dangerous since the supplied options may be completely different to what is running, and imo success should mean 'launched with the supplied options'), c) kill the running one and then start both (surprising, imo, to kill something in 'launch').

- Similar considerations apply to `stop`. We should stop whichever isn't running, report a "not running" for the other, and exit successfully (`stop` is idempotent).

- What should happen when starting one fails? I reckon we should kill the other and exit with an error.

**Comment by rade** [comment]
Replaced by #962.
