### ISSUE TITLE
Enabling TLS removes proxy from `weave status` output

### ISSUE THREAD

**Issue by paulbellamy** [weaveworks/weave#876]
Because curl cannot connect to the proxy over TLS.

**Comment by paulbellamy** [comment]
I'm not really sure the best way to fix this. We could:
A) Have a separate port (or unix socket) for status queries.
B) Get the certs from the proxy and configure curl with them.

**Comment by paulbellamy** [comment]
I'm leaning towards having a unix socket for status queries.

**Comment by rade** [comment]
Let's just ditch the proxy from `weave status`.

**Comment by rade** [comment]
Umm. how does `launch-proxy` work? It calls `wait_for_status_ip`, just like `weave status`.

**Comment by rade** [comment]
> how does `launch-proxy` work?

I'm guessing it 'works' because it can establish a connection, post something, and receive some tls nonsense.

> I'm leaning towards having a unix socket for status queries.

Speaking to unix sockets from the command line is a pain. There is no single, widely installed command for it. And `status` is a rather important command, so we want it to work with `weave --local` w/o users having to install exotic packages.

We could listen on 127.0.0.1:some_port, but listening on a fixed port is problematic, and making it configurable is a pain.

**Comment by paulbellamy** [comment]
Yep. The http_call_ip doesn't care what the response says, just that it can connect.
