### ISSUE TITLE
make `--with-ipam` the default

### ISSUE THREAD

**Issue by rade** [weaveworks/weave#940]
now that IPAM and DNS are the default everywhere, having to launch the proxy with `--with-ipam` in order to get automatic allocation when no address is specified, is a tad annoying. Just look at how much it gets in the way of the [example](http://docs.weave.works/weave/master/ae5c2dab86e6a31e21fe9fd62ddab3947f654030/proxy.html#multi-host).

Now, we still want a way to turn this off. We could introduce a `--without-ipam/with-ipam` combo, with the default determined by whether IPAM is running, but it usually will be, since there is no harm having it there and just not use it. So `--no-ipam`? Though that could be misleading since we'd still want this to use IPAM when `WEAVE_CIDR=` etc is specified. `--no-default-ipam`?

**Comment by paulbellamy** [comment]
At the moment there is no way to detect if ipam is enabled, so we will need to add that. Can find that out from `weave status`.

If we have that, I would say that enabling/disabling ipam in the router should be all you need to do. On top of that a `--no-default-ipam` flag if users want to boot containers unattached to the weave network (maybe `--no-auto-attach`?).

If ipam is disabled in the router, then `-e WEAVE_CIDR=` will be an error. If `--no-default-ipam` is passed, then it means "use IPAM to attach this node".

We'll need to do a bit extra handling around weavewait, because you may create a container without ipam (and no weave_cidr), then start it with ipam running (or vice versa).

**Comment by paulbellamy** [comment]
per f2f discussion:
No auto-detection for this release, as disabling IPAM is a undocumented usage. We assume IPAM is always enabled.

Provide an out with the `--no-default-ipam` flag, meaning do not attach nodes with no `WEAVE_CIDR` specified. IPAM can still be explicitly used by specifying `-e WEAVE_CIDR=`

**Comment by paulbellamy** [comment]
Another option is to have a `-e WEAVE_CIDR=none`, so even if ipam is normally enabled, you can disable weave networking for a specific container. But this is probably not necessary for this release.
