### ISSUE TITLE
Have `weave attach|expose|detach|hide` print all addresses to stdout

### ISSUE THREAD

**Issue by awh** [weaveworks/weave#954]
These commands complete silently even when they have allocated IP addresses, requiring a second step of `weave ps` to find out what has been assigned. It would be useful to be able to capture the IP in a similar way to the technique used with `weave run` e.g:

```
$ EXPOSED_IP=$(weave expose)
```

**Comment by rade** [comment]
I reckon these should output *all* addresses, allocated or not.

**Comment by rade** [comment]
NB: *addresses* only. no `/nn` routing prefix length.

**Comment by rade** [comment]
Should these commands only show addresses that were *actually* getting associated / dissociated? ie. exclude already associated/dissociated addresses? IMO no; these commands should be idempotent and produce the same results (modulo variations due to different allocations) regardless of context. This also implies that they should only show addresses we actually *attempted* to associate; not any other addresses that may already by associated.

Should the output be uniq`ified? e.g. say a user supplied the same address multiple times, or specified both `net:default` and `net:<the-default-subnet>`? IMO no; though I don't have a particularly strong rationale either way.
