### ISSUE TITLE
breakage when container names are syntactically invalid as hostnames 

### ISSUE THREAD

**Issue by errordeveloper** [weaveworks/weave#961]
For example, Compose generates names with underscores.

**Comment by rade** [comment]
@errordeveloper what is the actual problem here? I tried...

````
$ weave launch && weave launch-dns && weave launch-proxy
233175e68b3f1acdb4b575365b65873bb4e6f2fdde4540ee58fb5a940fa1cc0e
eab7f5de2f66576835a4e119570304ab16b6bbae26a8f752315d46b6c5d29e53
9f22c0618999ba92de2ca1fe038ca6700470e6ee5a5c3e6b8adae7772c23deaf
$ eval $(weave proxy-env)
$ docker run --name=a_1 -ti ubuntu
root@a_1:/#
````
which works just fine.

**Comment by rade** [comment]
[Apparently](https://en.wikipedia.org/wiki/Hostname#Restrictions_on_valid_host_names) the restriction is that hostname components may contain only the ASCII letters 'a' through 'z' (in a case-insensitive manner), the digits '0' through '9', and the hyphen ('-'), and must not start or end in a hyphen.

So underscores are indeed not valid. However, I'd quite like to know what actually broke for @errordeveloper, so we can be sure that we are solving a real rather than theoretical problem here. I've tried `gliderlabs/alpine' and, just like ubuntu, it is perfectly happy with underscores.

**Comment by errordeveloper** [comment]
@rade indeed, so far this was a theoretical one. I didn't see anything breaking specifically, it looks like the `_` in DNS names is widely accepted.
